/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_HUNYUAN_V20230901_MODEL_SUBMITHUNYUAN3DPARTJOBREQUEST_H_
#define TENCENTCLOUD_HUNYUAN_V20230901_MODEL_SUBMITHUNYUAN3DPARTJOBREQUEST_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/AbstractModel.h>
#include <tencentcloud/hunyuan/v20230901/model/InputFile3D.h>


namespace TencentCloud
{
    namespace Hunyuan
    {
        namespace V20230901
        {
            namespace Model
            {
                /**
                * SubmitHunyuan3DPartJob request structure.
                */
                class SubmitHunyuan3DPartJobRequest : public AbstractModel
                {
                public:
                    SubmitHunyuan3DPartJobRequest();
                    ~SubmitHunyuan3DPartJobRequest() = default;
                    std::string ToJsonString() const;


                    /**
                     * 获取Recommends inputting 3D models generated by AIGC
Recommended file size not greater than 100MB
Face count not greater than 30,000
Only supports FBX format
                     * @return File Recommends inputting 3D models generated by AIGC
Recommended file size not greater than 100MB
Face count not greater than 30,000
Only supports FBX format
                     * 
                     */
                    InputFile3D GetFile() const;

                    /**
                     * 设置Recommends inputting 3D models generated by AIGC
Recommended file size not greater than 100MB
Face count not greater than 30,000
Only supports FBX format
                     * @param _file Recommends inputting 3D models generated by AIGC
Recommended file size not greater than 100MB
Face count not greater than 30,000
Only supports FBX format
                     * 
                     */
                    void SetFile(const InputFile3D& _file);

                    /**
                     * 判断参数 File 是否已赋值
                     * @return File 是否已赋值
                     * 
                     */
                    bool FileHasBeenSet() const;

                private:

                    /**
                     * Recommends inputting 3D models generated by AIGC
Recommended file size not greater than 100MB
Face count not greater than 30,000
Only supports FBX format
                     */
                    InputFile3D m_file;
                    bool m_fileHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_HUNYUAN_V20230901_MODEL_SUBMITHUNYUAN3DPARTJOBREQUEST_H_
