/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_HUNYUAN_V20230901_MODEL_SUBMIT3DSMARTTOPOLOGYJOBREQUEST_H_
#define TENCENTCLOUD_HUNYUAN_V20230901_MODEL_SUBMIT3DSMARTTOPOLOGYJOBREQUEST_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/AbstractModel.h>
#include <tencentcloud/hunyuan/v20230901/model/InputFile3D.h>


namespace TencentCloud
{
    namespace Hunyuan
    {
        namespace V20230901
        {
            namespace Model
            {
                /**
                * Submit3DSmartTopologyJob request structure.
                */
                class Submit3DSmartTopologyJobRequest : public AbstractModel
                {
                public:
                    Submit3DSmartTopologyJobRequest();
                    ~Submit3DSmartTopologyJobRequest() = default;
                    std::string ToJsonString() const;


                    /**
                     * 获取Source 3D file model link
Reference value:glb,obj
One of the file formats is required.
Url: file size cannot exceed 200MB.
3D model requirements: complex models and topologized models do not support face reduction. recommended input is non-topologized high-poly models, such as those generated by hunyuan 3d. high applicability categories include hard surface, game character, prop, daily objects.
                     * @return File3D Source 3D file model link
Reference value:glb,obj
One of the file formats is required.
Url: file size cannot exceed 200MB.
3D model requirements: complex models and topologized models do not support face reduction. recommended input is non-topologized high-poly models, such as those generated by hunyuan 3d. high applicability categories include hard surface, game character, prop, daily objects.
                     * 
                     */
                    InputFile3D GetFile3D() const;

                    /**
                     * 设置Source 3D file model link
Reference value:glb,obj
One of the file formats is required.
Url: file size cannot exceed 200MB.
3D model requirements: complex models and topologized models do not support face reduction. recommended input is non-topologized high-poly models, such as those generated by hunyuan 3d. high applicability categories include hard surface, game character, prop, daily objects.
                     * @param _file3D Source 3D file model link
Reference value:glb,obj
One of the file formats is required.
Url: file size cannot exceed 200MB.
3D model requirements: complex models and topologized models do not support face reduction. recommended input is non-topologized high-poly models, such as those generated by hunyuan 3d. high applicability categories include hard surface, game character, prop, daily objects.
                     * 
                     */
                    void SetFile3D(const InputFile3D& _file3D);

                    /**
                     * 判断参数 File3D 是否已赋值
                     * @return File3D 是否已赋值
                     * 
                     */
                    bool File3DHasBeenSet() const;

                    /**
                     * 获取Polygon type, indicates the model surface is composed of grid components, defaults to triangle
Reference value:
triangle: triangle face
quadrilateral: triangular and quadrilateral mixed face
                     * @return PolygonType Polygon type, indicates the model surface is composed of grid components, defaults to triangle
Reference value:
triangle: triangle face
quadrilateral: triangular and quadrilateral mixed face
                     * 
                     */
                    std::string GetPolygonType() const;

                    /**
                     * 设置Polygon type, indicates the model surface is composed of grid components, defaults to triangle
Reference value:
triangle: triangle face
quadrilateral: triangular and quadrilateral mixed face
                     * @param _polygonType Polygon type, indicates the model surface is composed of grid components, defaults to triangle
Reference value:
triangle: triangle face
quadrilateral: triangular and quadrilateral mixed face
                     * 
                     */
                    void SetPolygonType(const std::string& _polygonType);

                    /**
                     * 判断参数 PolygonType 是否已赋值
                     * @return PolygonType 是否已赋值
                     * 
                     */
                    bool PolygonTypeHasBeenSet() const;

                    /**
                     * 获取Reduction level bit type
valid values: high, medium, low
                     * @return FaceLevel Reduction level bit type
valid values: high, medium, low
                     * 
                     */
                    std::string GetFaceLevel() const;

                    /**
                     * 设置Reduction level bit type
valid values: high, medium, low
                     * @param _faceLevel Reduction level bit type
valid values: high, medium, low
                     * 
                     */
                    void SetFaceLevel(const std::string& _faceLevel);

                    /**
                     * 判断参数 FaceLevel 是否已赋值
                     * @return FaceLevel 是否已赋值
                     * 
                     */
                    bool FaceLevelHasBeenSet() const;

                private:

                    /**
                     * Source 3D file model link
Reference value:glb,obj
One of the file formats is required.
Url: file size cannot exceed 200MB.
3D model requirements: complex models and topologized models do not support face reduction. recommended input is non-topologized high-poly models, such as those generated by hunyuan 3d. high applicability categories include hard surface, game character, prop, daily objects.
                     */
                    InputFile3D m_file3D;
                    bool m_file3DHasBeenSet;

                    /**
                     * Polygon type, indicates the model surface is composed of grid components, defaults to triangle
Reference value:
triangle: triangle face
quadrilateral: triangular and quadrilateral mixed face
                     */
                    std::string m_polygonType;
                    bool m_polygonTypeHasBeenSet;

                    /**
                     * Reduction level bit type
valid values: high, medium, low
                     */
                    std::string m_faceLevel;
                    bool m_faceLevelHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_HUNYUAN_V20230901_MODEL_SUBMIT3DSMARTTOPOLOGYJOBREQUEST_H_
