/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_HUNYUAN_V20230901_MODEL_SUBMITCONVERT3DFORMATJOBREQUEST_H_
#define TENCENTCLOUD_HUNYUAN_V20230901_MODEL_SUBMITCONVERT3DFORMATJOBREQUEST_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/AbstractModel.h>
#include <tencentcloud/hunyuan/v20230901/model/InputFile3D.h>


namespace TencentCloud
{
    namespace Hunyuan
    {
        namespace V20230901
        {
            namespace Model
            {
                /**
                * SubmitConvert3DFormatJob request structure.
                */
                class SubmitConvert3DFormatJobRequest : public AbstractModel
                {
                public:
                    SubmitConvert3DFormatJobRequest();
                    ~SubmitConvert3DFormatJobRequest() = default;
                    std::string ToJsonString() const;


                    /**
                     * 获取3D file URL address. The model file size should be less than 200MB;
Supports 3D file inputs in FBX, OBJ, and GLB formats;
For the OBJ format, a compressed package URL must be uploaded, containing URLs for the obj and mtl 3D model files, as well as texture maps;
It is recommended to upload OBJ models generated by HY-3D.
                     * @return File 3D file URL address. The model file size should be less than 200MB;
Supports 3D file inputs in FBX, OBJ, and GLB formats;
For the OBJ format, a compressed package URL must be uploaded, containing URLs for the obj and mtl 3D model files, as well as texture maps;
It is recommended to upload OBJ models generated by HY-3D.
                     * 
                     */
                    InputFile3D GetFile() const;

                    /**
                     * 设置3D file URL address. The model file size should be less than 200MB;
Supports 3D file inputs in FBX, OBJ, and GLB formats;
For the OBJ format, a compressed package URL must be uploaded, containing URLs for the obj and mtl 3D model files, as well as texture maps;
It is recommended to upload OBJ models generated by HY-3D.
                     * @param _file 3D file URL address. The model file size should be less than 200MB;
Supports 3D file inputs in FBX, OBJ, and GLB formats;
For the OBJ format, a compressed package URL must be uploaded, containing URLs for the obj and mtl 3D model files, as well as texture maps;
It is recommended to upload OBJ models generated by HY-3D.
                     * 
                     */
                    void SetFile(const InputFile3D& _file);

                    /**
                     * 判断参数 File 是否已赋值
                     * @return File 是否已赋值
                     * 
                     */
                    bool FileHasBeenSet() const;

                    /**
                     * 获取Returns the 3D file format. valid values:
STL, USDZ, FBX, MP4, GIF;
Example value: STL.
                     * @return Format Returns the 3D file format. valid values:
STL, USDZ, FBX, MP4, GIF;
Example value: STL.
                     * 
                     */
                    std::string GetFormat() const;

                    /**
                     * 设置Returns the 3D file format. valid values:
STL, USDZ, FBX, MP4, GIF;
Example value: STL.
                     * @param _format Returns the 3D file format. valid values:
STL, USDZ, FBX, MP4, GIF;
Example value: STL.
                     * 
                     */
                    void SetFormat(const std::string& _format);

                    /**
                     * 判断参数 Format 是否已赋值
                     * @return Format 是否已赋值
                     * 
                     */
                    bool FormatHasBeenSet() const;

                private:

                    /**
                     * 3D file URL address. The model file size should be less than 200MB;
Supports 3D file inputs in FBX, OBJ, and GLB formats;
For the OBJ format, a compressed package URL must be uploaded, containing URLs for the obj and mtl 3D model files, as well as texture maps;
It is recommended to upload OBJ models generated by HY-3D.
                     */
                    InputFile3D m_file;
                    bool m_fileHasBeenSet;

                    /**
                     * Returns the 3D file format. valid values:
STL, USDZ, FBX, MP4, GIF;
Example value: STL.
                     */
                    std::string m_format;
                    bool m_formatHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_HUNYUAN_V20230901_MODEL_SUBMITCONVERT3DFORMATJOBREQUEST_H_
