/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_VOD_V20180717_MODEL_AIGCVIDEOTASKUSAGE_H_
#define TENCENTCLOUD_VOD_V20180717_MODEL_AIGCVIDEOTASKUSAGE_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/utils/rapidjson/document.h>
#include <tencentcloud/core/utils/rapidjson/writer.h>
#include <tencentcloud/core/utils/rapidjson/stringbuffer.h>
#include <tencentcloud/core/AbstractModel.h>


namespace TencentCloud
{
    namespace Vod
    {
        namespace V20180717
        {
            namespace Model
            {
                /**
                * Amount of AIGC video tasks.
                */
                class AigcVideoTaskUsage : public AbstractModel
                {
                public:
                    AigcVideoTaskUsage();
                    ~AigcVideoTaskUsage() = default;
                    void ToJsonObject(rapidjson::Value &value, rapidjson::Document::AllocatorType& allocator) const;
                    CoreInternalOutcome Deserialize(const rapidjson::Value &value);


                    /**
                     * 获取<p>Input the number of tokens.</p><p>Valid only when using the omni version of GV.</p>
                     * @return InputTokens <p>Input the number of tokens.</p><p>Valid only when using the omni version of GV.</p>
                     * 
                     */
                    int64_t GetInputTokens() const;

                    /**
                     * 设置<p>Input the number of tokens.</p><p>Valid only when using the omni version of GV.</p>
                     * @param _inputTokens <p>Input the number of tokens.</p><p>Valid only when using the omni version of GV.</p>
                     * 
                     */
                    void SetInputTokens(const int64_t& _inputTokens);

                    /**
                     * 判断参数 InputTokens 是否已赋值
                     * @return InputTokens 是否已赋值
                     * 
                     */
                    bool InputTokensHasBeenSet() const;

                    /**
                     * 获取<p>Number of tokens generated by thinking.</p><p>Valid only when using the omni version of GV.</p>
                     * @return ThoughtTokens <p>Number of tokens generated by thinking.</p><p>Valid only when using the omni version of GV.</p>
                     * 
                     */
                    int64_t GetThoughtTokens() const;

                    /**
                     * 设置<p>Number of tokens generated by thinking.</p><p>Valid only when using the omni version of GV.</p>
                     * @param _thoughtTokens <p>Number of tokens generated by thinking.</p><p>Valid only when using the omni version of GV.</p>
                     * 
                     */
                    void SetThoughtTokens(const int64_t& _thoughtTokens);

                    /**
                     * 判断参数 ThoughtTokens 是否已赋值
                     * @return ThoughtTokens 是否已赋值
                     * 
                     */
                    bool ThoughtTokensHasBeenSet() const;

                    /**
                     * 获取<p>Number of input images.</p><p>Valid only when using the H3 version of Hailuo.</p>
                     * @return InputImageCount <p>Number of input images.</p><p>Valid only when using the H3 version of Hailuo.</p>
                     * 
                     */
                    int64_t GetInputImageCount() const;

                    /**
                     * 设置<p>Number of input images.</p><p>Valid only when using the H3 version of Hailuo.</p>
                     * @param _inputImageCount <p>Number of input images.</p><p>Valid only when using the H3 version of Hailuo.</p>
                     * 
                     */
                    void SetInputImageCount(const int64_t& _inputImageCount);

                    /**
                     * 判断参数 InputImageCount 是否已赋值
                     * @return InputImageCount 是否已赋值
                     * 
                     */
                    bool InputImageCountHasBeenSet() const;

                    /**
                     * 获取<p>Duration of the input video.</p><p>Unit: seconds.</p><p>Valid only when using the H3 version of Hailuo.</p>
                     * @return InputSeconds <p>Duration of the input video.</p><p>Unit: seconds.</p><p>Valid only when using the H3 version of Hailuo.</p>
                     * 
                     */
                    int64_t GetInputSeconds() const;

                    /**
                     * 设置<p>Duration of the input video.</p><p>Unit: seconds.</p><p>Valid only when using the H3 version of Hailuo.</p>
                     * @param _inputSeconds <p>Duration of the input video.</p><p>Unit: seconds.</p><p>Valid only when using the H3 version of Hailuo.</p>
                     * 
                     */
                    void SetInputSeconds(const int64_t& _inputSeconds);

                    /**
                     * 判断参数 InputSeconds 是否已赋值
                     * @return InputSeconds 是否已赋值
                     * 
                     */
                    bool InputSecondsHasBeenSet() const;

                    /**
                     * 获取<p>Output video duration.</p><p>Unit: seconds.</p><p>Valid only when using the H3 version of Hailuo.</p>
                     * @return OutputSeconds <p>Output video duration.</p><p>Unit: seconds.</p><p>Valid only when using the H3 version of Hailuo.</p>
                     * 
                     */
                    int64_t GetOutputSeconds() const;

                    /**
                     * 设置<p>Output video duration.</p><p>Unit: seconds.</p><p>Valid only when using the H3 version of Hailuo.</p>
                     * @param _outputSeconds <p>Output video duration.</p><p>Unit: seconds.</p><p>Valid only when using the H3 version of Hailuo.</p>
                     * 
                     */
                    void SetOutputSeconds(const int64_t& _outputSeconds);

                    /**
                     * 判断参数 OutputSeconds 是否已赋值
                     * @return OutputSeconds 是否已赋值
                     * 
                     */
                    bool OutputSecondsHasBeenSet() const;

                    /**
                     * 获取<p>Total input and output duration.</p><p>Default value: seconds.</p><p>Valid only when using Hailuo H3 version.</p>
                     * @return TotalSeconds <p>Total input and output duration.</p><p>Default value: seconds.</p><p>Valid only when using Hailuo H3 version.</p>
                     * 
                     */
                    int64_t GetTotalSeconds() const;

                    /**
                     * 设置<p>Total input and output duration.</p><p>Default value: seconds.</p><p>Valid only when using Hailuo H3 version.</p>
                     * @param _totalSeconds <p>Total input and output duration.</p><p>Default value: seconds.</p><p>Valid only when using Hailuo H3 version.</p>
                     * 
                     */
                    void SetTotalSeconds(const int64_t& _totalSeconds);

                    /**
                     * 判断参数 TotalSeconds 是否已赋值
                     * @return TotalSeconds 是否已赋值
                     * 
                     */
                    bool TotalSecondsHasBeenSet() const;

                private:

                    /**
                     * <p>Input the number of tokens.</p><p>Valid only when using the omni version of GV.</p>
                     */
                    int64_t m_inputTokens;
                    bool m_inputTokensHasBeenSet;

                    /**
                     * <p>Number of tokens generated by thinking.</p><p>Valid only when using the omni version of GV.</p>
                     */
                    int64_t m_thoughtTokens;
                    bool m_thoughtTokensHasBeenSet;

                    /**
                     * <p>Number of input images.</p><p>Valid only when using the H3 version of Hailuo.</p>
                     */
                    int64_t m_inputImageCount;
                    bool m_inputImageCountHasBeenSet;

                    /**
                     * <p>Duration of the input video.</p><p>Unit: seconds.</p><p>Valid only when using the H3 version of Hailuo.</p>
                     */
                    int64_t m_inputSeconds;
                    bool m_inputSecondsHasBeenSet;

                    /**
                     * <p>Output video duration.</p><p>Unit: seconds.</p><p>Valid only when using the H3 version of Hailuo.</p>
                     */
                    int64_t m_outputSeconds;
                    bool m_outputSecondsHasBeenSet;

                    /**
                     * <p>Total input and output duration.</p><p>Default value: seconds.</p><p>Valid only when using Hailuo H3 version.</p>
                     */
                    int64_t m_totalSeconds;
                    bool m_totalSecondsHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_VOD_V20180717_MODEL_AIGCVIDEOTASKUSAGE_H_
