/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_VOD_V20180717_MODEL_MEDIADELETEITEM_H_
#define TENCENTCLOUD_VOD_V20180717_MODEL_MEDIADELETEITEM_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/utils/rapidjson/document.h>
#include <tencentcloud/core/utils/rapidjson/writer.h>
#include <tencentcloud/core/utils/rapidjson/stringbuffer.h>
#include <tencentcloud/core/AbstractModel.h>


namespace TencentCloud
{
    namespace Vod
    {
        namespace V20180717
        {
            namespace Model
            {
                /**
                * Deletion content when specifying deletion of on-demand video
                */
                class MediaDeleteItem : public AbstractModel
                {
                public:
                    MediaDeleteItem();
                    ~MediaDeleteItem() = default;
                    void ToJsonObject(rapidjson::Value &value, rapidjson::Document::AllocatorType& allocator) const;
                    CoreInternalOutcome Deserialize(const rapidjson::Value &value);


                    /**
                     * 获取<p>The specified deletion part. If this field is not filled in, the parameter is invalid. Optional values:</p><li>OriginalFiles (delete the original file. Once deleted, any video processing operations such as transcode and publishing on WeChat cannot be initiated);</li><li>TranscodeFiles (delete transcoded files);</li><li>AdaptiveDynamicStreamingFiles (delete adaptive bitrate stream files);</li><li>WechatPublishFiles (delete files published on WeChat);</li><li>WechatMiniProgramPublishFiles (delete WeChat Mini Program Publishing files).</li><li>MpsAiMediaAiAnalysisFiles (delete AI analysis products generated by ProcessMediaByMPS).</li><li>MpsAiMediaSmartEraseFiles (delete intelligent erasure products generated by ProcessMediaByMPS).</li><li>MpsAiMediaSmartSubtitleFiles (delete smart subtitling products generated by ProcessMediaByMPS).</li><font color="red">Note:</font> <li>When the value is OriginalFiles, the cover file carried during file upload will be deleted;</li><li>When the value is TranscodeFiles, the cover file generated by media processing will be deleted.</li>
                     * @return Type <p>The specified deletion part. If this field is not filled in, the parameter is invalid. Optional values:</p><li>OriginalFiles (delete the original file. Once deleted, any video processing operations such as transcode and publishing on WeChat cannot be initiated);</li><li>TranscodeFiles (delete transcoded files);</li><li>AdaptiveDynamicStreamingFiles (delete adaptive bitrate stream files);</li><li>WechatPublishFiles (delete files published on WeChat);</li><li>WechatMiniProgramPublishFiles (delete WeChat Mini Program Publishing files).</li><li>MpsAiMediaAiAnalysisFiles (delete AI analysis products generated by ProcessMediaByMPS).</li><li>MpsAiMediaSmartEraseFiles (delete intelligent erasure products generated by ProcessMediaByMPS).</li><li>MpsAiMediaSmartSubtitleFiles (delete smart subtitling products generated by ProcessMediaByMPS).</li><font color="red">Note:</font> <li>When the value is OriginalFiles, the cover file carried during file upload will be deleted;</li><li>When the value is TranscodeFiles, the cover file generated by media processing will be deleted.</li>
                     * 
                     */
                    std::string GetType() const;

                    /**
                     * 设置<p>The specified deletion part. If this field is not filled in, the parameter is invalid. Optional values:</p><li>OriginalFiles (delete the original file. Once deleted, any video processing operations such as transcode and publishing on WeChat cannot be initiated);</li><li>TranscodeFiles (delete transcoded files);</li><li>AdaptiveDynamicStreamingFiles (delete adaptive bitrate stream files);</li><li>WechatPublishFiles (delete files published on WeChat);</li><li>WechatMiniProgramPublishFiles (delete WeChat Mini Program Publishing files).</li><li>MpsAiMediaAiAnalysisFiles (delete AI analysis products generated by ProcessMediaByMPS).</li><li>MpsAiMediaSmartEraseFiles (delete intelligent erasure products generated by ProcessMediaByMPS).</li><li>MpsAiMediaSmartSubtitleFiles (delete smart subtitling products generated by ProcessMediaByMPS).</li><font color="red">Note:</font> <li>When the value is OriginalFiles, the cover file carried during file upload will be deleted;</li><li>When the value is TranscodeFiles, the cover file generated by media processing will be deleted.</li>
                     * @param _type <p>The specified deletion part. If this field is not filled in, the parameter is invalid. Optional values:</p><li>OriginalFiles (delete the original file. Once deleted, any video processing operations such as transcode and publishing on WeChat cannot be initiated);</li><li>TranscodeFiles (delete transcoded files);</li><li>AdaptiveDynamicStreamingFiles (delete adaptive bitrate stream files);</li><li>WechatPublishFiles (delete files published on WeChat);</li><li>WechatMiniProgramPublishFiles (delete WeChat Mini Program Publishing files).</li><li>MpsAiMediaAiAnalysisFiles (delete AI analysis products generated by ProcessMediaByMPS).</li><li>MpsAiMediaSmartEraseFiles (delete intelligent erasure products generated by ProcessMediaByMPS).</li><li>MpsAiMediaSmartSubtitleFiles (delete smart subtitling products generated by ProcessMediaByMPS).</li><font color="red">Note:</font> <li>When the value is OriginalFiles, the cover file carried during file upload will be deleted;</li><li>When the value is TranscodeFiles, the cover file generated by media processing will be deleted.</li>
                     * 
                     */
                    void SetType(const std::string& _type);

                    /**
                     * 判断参数 Type 是否已赋值
                     * @return Type 是否已赋值
                     * 
                     */
                    bool TypeHasBeenSet() const;

                    /**
                     * 获取<p>Delete the video template ID of the type specified by the Type parameter. For the template definition, see <a href="https://www.tencentcloud.com/document/product/266/33478?from_cn_redirect=1#.3Cspan-id-.3D-.22zm.22-.3E.3C.2Fspan.3E.E8.BD.AC.E7.A0.81.E6.A8.A1.E6.9D.BF">Transcoding Template</a>.<br>The default value is 0, which means to delete all videos of the type specified by the Type parameter.</p>
                     * @return Definition <p>Delete the video template ID of the type specified by the Type parameter. For the template definition, see <a href="https://www.tencentcloud.com/document/product/266/33478?from_cn_redirect=1#.3Cspan-id-.3D-.22zm.22-.3E.3C.2Fspan.3E.E8.BD.AC.E7.A0.81.E6.A8.A1.E6.9D.BF">Transcoding Template</a>.<br>The default value is 0, which means to delete all videos of the type specified by the Type parameter.</p>
                     * 
                     */
                    int64_t GetDefinition() const;

                    /**
                     * 设置<p>Delete the video template ID of the type specified by the Type parameter. For the template definition, see <a href="https://www.tencentcloud.com/document/product/266/33478?from_cn_redirect=1#.3Cspan-id-.3D-.22zm.22-.3E.3C.2Fspan.3E.E8.BD.AC.E7.A0.81.E6.A8.A1.E6.9D.BF">Transcoding Template</a>.<br>The default value is 0, which means to delete all videos of the type specified by the Type parameter.</p>
                     * @param _definition <p>Delete the video template ID of the type specified by the Type parameter. For the template definition, see <a href="https://www.tencentcloud.com/document/product/266/33478?from_cn_redirect=1#.3Cspan-id-.3D-.22zm.22-.3E.3C.2Fspan.3E.E8.BD.AC.E7.A0.81.E6.A8.A1.E6.9D.BF">Transcoding Template</a>.<br>The default value is 0, which means to delete all videos of the type specified by the Type parameter.</p>
                     * 
                     */
                    void SetDefinition(const int64_t& _definition);

                    /**
                     * 判断参数 Definition 是否已赋值
                     * @return Definition 是否已赋值
                     * 
                     */
                    bool DefinitionHasBeenSet() const;

                private:

                    /**
                     * <p>The specified deletion part. If this field is not filled in, the parameter is invalid. Optional values:</p><li>OriginalFiles (delete the original file. Once deleted, any video processing operations such as transcode and publishing on WeChat cannot be initiated);</li><li>TranscodeFiles (delete transcoded files);</li><li>AdaptiveDynamicStreamingFiles (delete adaptive bitrate stream files);</li><li>WechatPublishFiles (delete files published on WeChat);</li><li>WechatMiniProgramPublishFiles (delete WeChat Mini Program Publishing files).</li><li>MpsAiMediaAiAnalysisFiles (delete AI analysis products generated by ProcessMediaByMPS).</li><li>MpsAiMediaSmartEraseFiles (delete intelligent erasure products generated by ProcessMediaByMPS).</li><li>MpsAiMediaSmartSubtitleFiles (delete smart subtitling products generated by ProcessMediaByMPS).</li><font color="red">Note:</font> <li>When the value is OriginalFiles, the cover file carried during file upload will be deleted;</li><li>When the value is TranscodeFiles, the cover file generated by media processing will be deleted.</li>
                     */
                    std::string m_type;
                    bool m_typeHasBeenSet;

                    /**
                     * <p>Delete the video template ID of the type specified by the Type parameter. For the template definition, see <a href="https://www.tencentcloud.com/document/product/266/33478?from_cn_redirect=1#.3Cspan-id-.3D-.22zm.22-.3E.3C.2Fspan.3E.E8.BD.AC.E7.A0.81.E6.A8.A1.E6.9D.BF">Transcoding Template</a>.<br>The default value is 0, which means to delete all videos of the type specified by the Type parameter.</p>
                     */
                    int64_t m_definition;
                    bool m_definitionHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_VOD_V20180717_MODEL_MEDIADELETEITEM_H_
