/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_VOD_V20180717_MODEL_SEMANTICSSEARCHRESULT_H_
#define TENCENTCLOUD_VOD_V20180717_MODEL_SEMANTICSSEARCHRESULT_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/utils/rapidjson/document.h>
#include <tencentcloud/core/utils/rapidjson/writer.h>
#include <tencentcloud/core/utils/rapidjson/stringbuffer.h>
#include <tencentcloud/core/AbstractModel.h>


namespace TencentCloud
{
    namespace Vod
    {
        namespace V20180717
        {
            namespace Model
            {
                /**
                * Semantic search result.
                */
                class SemanticsSearchResult : public AbstractModel
                {
                public:
                    SemanticsSearchResult();
                    ~SemanticsSearchResult() = default;
                    void ToJsonObject(rapidjson::Value &value, rapidjson::Document::AllocatorType& allocator) const;
                    CoreInternalOutcome Deserialize(const rapidjson::Value &value);


                    /**
                     * 获取<p>Media file unique identifier ID.</p>
                     * @return FileId <p>Media file unique identifier ID.</p>
                     * 
                     */
                    std::string GetFileId() const;

                    /**
                     * 设置<p>Media file unique identifier ID.</p>
                     * @param _fileId <p>Media file unique identifier ID.</p>
                     * 
                     */
                    void SetFileId(const std::string& _fileId);

                    /**
                     * 判断参数 FileId 是否已赋值
                     * @return FileId 是否已赋值
                     * 
                     */
                    bool FileIdHasBeenSet() const;

                    /**
                     * 获取<p>Title generated by Intelligent Media Assets for the current video clip</p>
                     * @return Title <p>Title generated by Intelligent Media Assets for the current video clip</p>
                     * 
                     */
                    std::string GetTitle() const;

                    /**
                     * 设置<p>Title generated by Intelligent Media Assets for the current video clip</p>
                     * @param _title <p>Title generated by Intelligent Media Assets for the current video clip</p>
                     * 
                     */
                    void SetTitle(const std::string& _title);

                    /**
                     * 判断参数 Title 是否已赋值
                     * @return Title 是否已赋值
                     * 
                     */
                    bool TitleHasBeenSet() const;

                    /**
                     * 获取<p>Score of the video in this retrieval. A higher score indicates higher similarity to the retrieval value. Value ranges from 0 to 1.</p>
                     * @return Score <p>Score of the video in this retrieval. A higher score indicates higher similarity to the retrieval value. Value ranges from 0 to 1.</p>
                     * 
                     */
                    double GetScore() const;

                    /**
                     * 设置<p>Score of the video in this retrieval. A higher score indicates higher similarity to the retrieval value. Value ranges from 0 to 1.</p>
                     * @param _score <p>Score of the video in this retrieval. A higher score indicates higher similarity to the retrieval value. Value ranges from 0 to 1.</p>
                     * 
                     */
                    void SetScore(const double& _score);

                    /**
                     * 判断参数 Score 是否已赋值
                     * @return Score 是否已赋值
                     * 
                     */
                    bool ScoreHasBeenSet() const;

                    /**
                     * 获取<p>Start time of the video clip. Unit: seconds</p>
                     * @return StartTimeOffset <p>Start time of the video clip. Unit: seconds</p>
                     * 
                     */
                    double GetStartTimeOffset() const;

                    /**
                     * 设置<p>Start time of the video clip. Unit: seconds</p>
                     * @param _startTimeOffset <p>Start time of the video clip. Unit: seconds</p>
                     * 
                     */
                    void SetStartTimeOffset(const double& _startTimeOffset);

                    /**
                     * 判断参数 StartTimeOffset 是否已赋值
                     * @return StartTimeOffset 是否已赋值
                     * 
                     */
                    bool StartTimeOffsetHasBeenSet() const;

                    /**
                     * 获取<p>End time of the video segment, unit: seconds</p>
                     * @return EndTimeOffset <p>End time of the video segment, unit: seconds</p>
                     * 
                     */
                    double GetEndTimeOffset() const;

                    /**
                     * 设置<p>End time of the video segment, unit: seconds</p>
                     * @param _endTimeOffset <p>End time of the video segment, unit: seconds</p>
                     * 
                     */
                    void SetEndTimeOffset(const double& _endTimeOffset);

                    /**
                     * 判断参数 EndTimeOffset 是否已赋值
                     * @return EndTimeOffset 是否已赋值
                     * 
                     */
                    bool EndTimeOffsetHasBeenSet() const;

                private:

                    /**
                     * <p>Media file unique identifier ID.</p>
                     */
                    std::string m_fileId;
                    bool m_fileIdHasBeenSet;

                    /**
                     * <p>Title generated by Intelligent Media Assets for the current video clip</p>
                     */
                    std::string m_title;
                    bool m_titleHasBeenSet;

                    /**
                     * <p>Score of the video in this retrieval. A higher score indicates higher similarity to the retrieval value. Value ranges from 0 to 1.</p>
                     */
                    double m_score;
                    bool m_scoreHasBeenSet;

                    /**
                     * <p>Start time of the video clip. Unit: seconds</p>
                     */
                    double m_startTimeOffset;
                    bool m_startTimeOffsetHasBeenSet;

                    /**
                     * <p>End time of the video segment, unit: seconds</p>
                     */
                    double m_endTimeOffset;
                    bool m_endTimeOffsetHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_VOD_V20180717_MODEL_SEMANTICSSEARCHRESULT_H_
