/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_MQTT_V20240516_MODEL_DEVICEIDENTITYITEM_H_
#define TENCENTCLOUD_MQTT_V20240516_MODEL_DEVICEIDENTITYITEM_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/utils/rapidjson/document.h>
#include <tencentcloud/core/utils/rapidjson/writer.h>
#include <tencentcloud/core/utils/rapidjson/stringbuffer.h>
#include <tencentcloud/core/AbstractModel.h>
#include <tencentcloud/mqtt/v20240516/model/PropagatingProperty.h>


namespace TencentCloud
{
    namespace Mqtt
    {
        namespace V20240516
        {
            namespace Model
            {
                /**
                * Device identifier list
                */
                class DeviceIdentityItem : public AbstractModel
                {
                public:
                    DeviceIdentityItem();
                    ~DeviceIdentityItem() = default;
                    void ToJsonObject(rapidjson::Value &value, rapidjson::Document::AllocatorType& allocator) const;
                    CoreInternalOutcome Deserialize(const rapidjson::Value &value);


                    /**
                     * 获取Cluster ID.
                     * @return InstanceId Cluster ID.
                     * 
                     */
                    std::string GetInstanceId() const;

                    /**
                     * 设置Cluster ID.
                     * @param _instanceId Cluster ID.
                     * 
                     */
                    void SetInstanceId(const std::string& _instanceId);

                    /**
                     * 判断参数 InstanceId 是否已赋值
                     * @return InstanceId 是否已赋值
                     * 
                     */
                    bool InstanceIdHasBeenSet() const;

                    /**
                     * 获取Device ID
                     * @return DeviceId Device ID
                     * 
                     */
                    std::string GetDeviceId() const;

                    /**
                     * 设置Device ID
                     * @param _deviceId Device ID
                     * 
                     */
                    void SetDeviceId(const std::string& _deviceId);

                    /**
                     * 判断参数 DeviceId 是否已赋值
                     * @return DeviceId 是否已赋值
                     * 
                     */
                    bool DeviceIdHasBeenSet() const;

                    /**
                     * 获取1: ENABLED - Available 2: DISABLED - Unavailable
                     * @return Status 1: ENABLED - Available 2: DISABLED - Unavailable
                     * 
                     */
                    int64_t GetStatus() const;

                    /**
                     * 设置1: ENABLED - Available 2: DISABLED - Unavailable
                     * @param _status 1: ENABLED - Available 2: DISABLED - Unavailable
                     * 
                     */
                    void SetStatus(const int64_t& _status);

                    /**
                     * 判断参数 Status 是否已赋值
                     * @return Status 是否已赋值
                     * 
                     */
                    bool StatusHasBeenSet() const;

                    /**
                     * 获取Primary signature key. Automatically generated by the system if not provided.
                     * @return PrimaryKey Primary signature key. Automatically generated by the system if not provided.
                     * 
                     */
                    std::string GetPrimaryKey() const;

                    /**
                     * 设置Primary signature key. Automatically generated by the system if not provided.
                     * @param _primaryKey Primary signature key. Automatically generated by the system if not provided.
                     * 
                     */
                    void SetPrimaryKey(const std::string& _primaryKey);

                    /**
                     * 判断参数 PrimaryKey 是否已赋值
                     * @return PrimaryKey 是否已赋值
                     * 
                     */
                    bool PrimaryKeyHasBeenSet() const;

                    /**
                     * 获取Secondary signature key. Automatically generated by the system if not passed.
                     * @return SecondaryKey Secondary signature key. Automatically generated by the system if not passed.
                     * 
                     */
                    std::string GetSecondaryKey() const;

                    /**
                     * 设置Secondary signature key. Automatically generated by the system if not passed.
                     * @param _secondaryKey Secondary signature key. Automatically generated by the system if not passed.
                     * 
                     */
                    void SetSecondaryKey(const std::string& _secondaryKey);

                    /**
                     * 判断参数 SecondaryKey 是否已赋值
                     * @return SecondaryKey 是否已赋值
                     * 
                     */
                    bool SecondaryKeyHasBeenSet() const;

                    /**
                     * 获取Creation time.
                     * @return CreatedTime Creation time.
                     * 
                     */
                    int64_t GetCreatedTime() const;

                    /**
                     * 设置Creation time.
                     * @param _createdTime Creation time.
                     * 
                     */
                    void SetCreatedTime(const int64_t& _createdTime);

                    /**
                     * 判断参数 CreatedTime 是否已赋值
                     * @return CreatedTime 是否已赋值
                     * 
                     */
                    bool CreatedTimeHasBeenSet() const;

                    /**
                     * 获取Spread attribute list
                     * @return PropagatingProperties Spread attribute list
                     * 
                     */
                    std::vector<PropagatingProperty> GetPropagatingProperties() const;

                    /**
                     * 设置Spread attribute list
                     * @param _propagatingProperties Spread attribute list
                     * 
                     */
                    void SetPropagatingProperties(const std::vector<PropagatingProperty>& _propagatingProperties);

                    /**
                     * 判断参数 PropagatingProperties 是否已赋值
                     * @return PropagatingProperties 是否已赋值
                     * 
                     */
                    bool PropagatingPropertiesHasBeenSet() const;

                private:

                    /**
                     * Cluster ID.
                     */
                    std::string m_instanceId;
                    bool m_instanceIdHasBeenSet;

                    /**
                     * Device ID
                     */
                    std::string m_deviceId;
                    bool m_deviceIdHasBeenSet;

                    /**
                     * 1: ENABLED - Available 2: DISABLED - Unavailable
                     */
                    int64_t m_status;
                    bool m_statusHasBeenSet;

                    /**
                     * Primary signature key. Automatically generated by the system if not provided.
                     */
                    std::string m_primaryKey;
                    bool m_primaryKeyHasBeenSet;

                    /**
                     * Secondary signature key. Automatically generated by the system if not passed.
                     */
                    std::string m_secondaryKey;
                    bool m_secondaryKeyHasBeenSet;

                    /**
                     * Creation time.
                     */
                    int64_t m_createdTime;
                    bool m_createdTimeHasBeenSet;

                    /**
                     * Spread attribute list
                     */
                    std::vector<PropagatingProperty> m_propagatingProperties;
                    bool m_propagatingPropertiesHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_MQTT_V20240516_MODEL_DEVICEIDENTITYITEM_H_
