/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_CAPTCHA_V20190722_MODEL_DESCRIBECAPTCHARESULTRESPONSE_H_
#define TENCENTCLOUD_CAPTCHA_V20190722_MODEL_DESCRIBECAPTCHARESULTRESPONSE_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/AbstractModel.h>


namespace TencentCloud
{
    namespace Captcha
    {
        namespace V20190722
        {
            namespace Model
            {
                /**
                * DescribeCaptchaResult response structure.
                */
                class DescribeCaptchaResultResponse : public AbstractModel
                {
                public:
                    DescribeCaptchaResultResponse();
                    ~DescribeCaptchaResultResponse() = default;
                    CoreInternalOutcome Deserialize(const std::string &payload);
                    std::string ToJsonString() const;


                    /**
                     * 获取<p>1 OK verification passed<br>7 captcha no match The passed-in Randstr is invalid. Please check whether Randstr is consistent with the frontend Randstr.<br>8 ticket expired The passed-in ticket has expired (ticket valid period is 5 minutes). Please generate a new ticket and Randstr for verification.<br>9 ticket reused The passed-in ticket has been reused. Please generate a new ticket and Randstr for verification.<br>15 decrypt fail The passed-in ticket is invalid. Please check whether ticket is consistent with the frontend ticket.<br>16 appid-ticket mismatch The passed-in CaptchaAppId is incorrect. Please check whether CaptchaAppId is consistent with the frontend CaptchaAppId, and ensure that CaptchaAppId is obtained from [Verification Management] -> [Basic Configuration] in the verification code console.<br>21 diff Bill verification exception. Possible reasons: (1) If the ticket contains the trerror prefix, it is generally because the user has a poor network connection, which causes frontend automatic disaster recovery and generates a disaster recovery ticket. The business side can skip or post-process it based on needs. (2) If the ticket does not contain the trerror prefix, it is because the verification code risk control system has detected a security risk in the request. The business side can block it based on needs.<br>100 appid-secretkey-ticket mismatch Parameter validation error. (1) Please check whether CaptchaAppId and AppSecretKey are correct. CaptchaAppId and AppSecretKey need to be obtained from [Verification Management] > [Basic Configuration] in the verification code console. (2) Please check whether the passed-in ticket is generated by the passed-in CaptchaAppId.</p>
                     * @return CaptchaCode <p>1 OK verification passed<br>7 captcha no match The passed-in Randstr is invalid. Please check whether Randstr is consistent with the frontend Randstr.<br>8 ticket expired The passed-in ticket has expired (ticket valid period is 5 minutes). Please generate a new ticket and Randstr for verification.<br>9 ticket reused The passed-in ticket has been reused. Please generate a new ticket and Randstr for verification.<br>15 decrypt fail The passed-in ticket is invalid. Please check whether ticket is consistent with the frontend ticket.<br>16 appid-ticket mismatch The passed-in CaptchaAppId is incorrect. Please check whether CaptchaAppId is consistent with the frontend CaptchaAppId, and ensure that CaptchaAppId is obtained from [Verification Management] -> [Basic Configuration] in the verification code console.<br>21 diff Bill verification exception. Possible reasons: (1) If the ticket contains the trerror prefix, it is generally because the user has a poor network connection, which causes frontend automatic disaster recovery and generates a disaster recovery ticket. The business side can skip or post-process it based on needs. (2) If the ticket does not contain the trerror prefix, it is because the verification code risk control system has detected a security risk in the request. The business side can block it based on needs.<br>100 appid-secretkey-ticket mismatch Parameter validation error. (1) Please check whether CaptchaAppId and AppSecretKey are correct. CaptchaAppId and AppSecretKey need to be obtained from [Verification Management] > [Basic Configuration] in the verification code console. (2) Please check whether the passed-in ticket is generated by the passed-in CaptchaAppId.</p>
                     * 
                     */
                    int64_t GetCaptchaCode() const;

                    /**
                     * 判断参数 CaptchaCode 是否已赋值
                     * @return CaptchaCode 是否已赋值
                     * 
                     */
                    bool CaptchaCodeHasBeenSet() const;

                    /**
                     * 获取<p>Description and error message</p>
                     * @return CaptchaMsg <p>Description and error message</p>
                     * 
                     */
                    std::string GetCaptchaMsg() const;

                    /**
                     * 判断参数 CaptchaMsg 是否已赋值
                     * @return CaptchaMsg 是否已赋值
                     * 
                     */
                    bool CaptchaMsgHasBeenSet() const;

                    /**
                     * 获取<p>In non-perception mode, this parameter returns the verification result:<br>EvilLevel=0: The request is not malicious<br>EvilLevel=100: The request is malicious</p>
                     * @return EvilLevel <p>In non-perception mode, this parameter returns the verification result:<br>EvilLevel=0: The request is not malicious<br>EvilLevel=100: The request is malicious</p>
                     * 
                     */
                    int64_t GetEvilLevel() const;

                    /**
                     * 判断参数 EvilLevel 是否已赋值
                     * @return EvilLevel 是否已赋值
                     * 
                     */
                    bool EvilLevelHasBeenSet() const;

                    /**
                     * 获取<p>Frontend verification code retrieval time, Timestamp Format</p>
                     * @return GetCaptchaTime <p>Frontend verification code retrieval time, Timestamp Format</p>
                     * 
                     */
                    int64_t GetGetCaptchaTime() const;

                    /**
                     * 判断参数 GetCaptchaTime 是否已赋值
                     * @return GetCaptchaTime 是否已赋值
                     * 
                     */
                    bool GetCaptchaTimeHasBeenSet() const;

                    /**
                     * 获取<p>Interception type</p>
                     * @return EvilBitmap <p>Interception type</p>
                     * 
                     */
                    int64_t GetEvilBitmap() const;

                    /**
                     * 判断参数 EvilBitmap 是否已赋值
                     * @return EvilBitmap 是否已赋值
                     * 
                     */
                    bool EvilBitmapHasBeenSet() const;

                    /**
                     * 获取<p>Time of submitting the verification code</p>
                     * @return SubmitCaptchaTime <p>Time of submitting the verification code</p>
                     * 
                     */
                    int64_t GetSubmitCaptchaTime() const;

                    /**
                     * 判断参数 SubmitCaptchaTime 是否已赋值
                     * @return SubmitCaptchaTime 是否已赋值
                     * 
                     */
                    bool SubmitCaptchaTimeHasBeenSet() const;

                    /**
                     * 获取<p>Device risk category</p>
                     * @return DeviceRiskCategory <p>Device risk category</p>
                     * 
                     */
                    std::string GetDeviceRiskCategory() const;

                    /**
                     * 判断参数 DeviceRiskCategory 是否已赋值
                     * @return DeviceRiskCategory 是否已赋值
                     * 
                     */
                    bool DeviceRiskCategoryHasBeenSet() const;

                    /**
                     * 获取<p>Verification code score</p><p>Value range: 0-100. Higher scores indicate higher risk</p>
                     * @return Score <p>Verification code score</p><p>Value range: 0-100. Higher scores indicate higher risk</p>
                     * 
                     */
                    int64_t GetScore() const;

                    /**
                     * 判断参数 Score 是否已赋值
                     * @return Score 是否已赋值
                     * 
                     */
                    bool ScoreHasBeenSet() const;

                private:

                    /**
                     * <p>1 OK verification passed<br>7 captcha no match The passed-in Randstr is invalid. Please check whether Randstr is consistent with the frontend Randstr.<br>8 ticket expired The passed-in ticket has expired (ticket valid period is 5 minutes). Please generate a new ticket and Randstr for verification.<br>9 ticket reused The passed-in ticket has been reused. Please generate a new ticket and Randstr for verification.<br>15 decrypt fail The passed-in ticket is invalid. Please check whether ticket is consistent with the frontend ticket.<br>16 appid-ticket mismatch The passed-in CaptchaAppId is incorrect. Please check whether CaptchaAppId is consistent with the frontend CaptchaAppId, and ensure that CaptchaAppId is obtained from [Verification Management] -> [Basic Configuration] in the verification code console.<br>21 diff Bill verification exception. Possible reasons: (1) If the ticket contains the trerror prefix, it is generally because the user has a poor network connection, which causes frontend automatic disaster recovery and generates a disaster recovery ticket. The business side can skip or post-process it based on needs. (2) If the ticket does not contain the trerror prefix, it is because the verification code risk control system has detected a security risk in the request. The business side can block it based on needs.<br>100 appid-secretkey-ticket mismatch Parameter validation error. (1) Please check whether CaptchaAppId and AppSecretKey are correct. CaptchaAppId and AppSecretKey need to be obtained from [Verification Management] > [Basic Configuration] in the verification code console. (2) Please check whether the passed-in ticket is generated by the passed-in CaptchaAppId.</p>
                     */
                    int64_t m_captchaCode;
                    bool m_captchaCodeHasBeenSet;

                    /**
                     * <p>Description and error message</p>
                     */
                    std::string m_captchaMsg;
                    bool m_captchaMsgHasBeenSet;

                    /**
                     * <p>In non-perception mode, this parameter returns the verification result:<br>EvilLevel=0: The request is not malicious<br>EvilLevel=100: The request is malicious</p>
                     */
                    int64_t m_evilLevel;
                    bool m_evilLevelHasBeenSet;

                    /**
                     * <p>Frontend verification code retrieval time, Timestamp Format</p>
                     */
                    int64_t m_getCaptchaTime;
                    bool m_getCaptchaTimeHasBeenSet;

                    /**
                     * <p>Interception type</p>
                     */
                    int64_t m_evilBitmap;
                    bool m_evilBitmapHasBeenSet;

                    /**
                     * <p>Time of submitting the verification code</p>
                     */
                    int64_t m_submitCaptchaTime;
                    bool m_submitCaptchaTimeHasBeenSet;

                    /**
                     * <p>Device risk category</p>
                     */
                    std::string m_deviceRiskCategory;
                    bool m_deviceRiskCategoryHasBeenSet;

                    /**
                     * <p>Verification code score</p><p>Value range: 0-100. Higher scores indicate higher risk</p>
                     */
                    int64_t m_score;
                    bool m_scoreHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_CAPTCHA_V20190722_MODEL_DESCRIBECAPTCHARESULTRESPONSE_H_
