/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_MPS_V20190612_MODEL_COSOUTPUTSTORAGE_H_
#define TENCENTCLOUD_MPS_V20190612_MODEL_COSOUTPUTSTORAGE_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/utils/rapidjson/document.h>
#include <tencentcloud/core/utils/rapidjson/writer.h>
#include <tencentcloud/core/utils/rapidjson/stringbuffer.h>
#include <tencentcloud/core/AbstractModel.h>


namespace TencentCloud
{
    namespace Mps
    {
        namespace V20190612
        {
            namespace Model
            {
                /**
                * Media processing COS output object information.
                */
                class CosOutputStorage : public AbstractModel
                {
                public:
                    CosOutputStorage();
                    ~CosOutputStorage() = default;
                    void ToJsonObject(rapidjson::Value &value, rapidjson::Document::AllocatorType& allocator) const;
                    CoreInternalOutcome Deserialize(const rapidjson::Value &value);


                    /**
                     * 获取Target Bucket name for the output files generated by media processing, for example, TopRankVideo-125xxx88. If left empty, the upper-level Bucket is inherited.
                     * @return Bucket Target Bucket name for the output files generated by media processing, for example, TopRankVideo-125xxx88. If left empty, the upper-level Bucket is inherited.
                     * 
                     */
                    std::string GetBucket() const;

                    /**
                     * 设置Target Bucket name for the output files generated by media processing, for example, TopRankVideo-125xxx88. If left empty, the upper-level Bucket is inherited.
                     * @param _bucket Target Bucket name for the output files generated by media processing, for example, TopRankVideo-125xxx88. If left empty, the upper-level Bucket is inherited.
                     * 
                     */
                    void SetBucket(const std::string& _bucket);

                    /**
                     * 判断参数 Bucket 是否已赋值
                     * @return Bucket 是否已赋值
                     * 
                     */
                    bool BucketHasBeenSet() const;

                    /**
                     * 获取Park of the target Bucket for outputting media processing generated files, for example, ap-chongqing. If left empty, it is inheritable from the upper layer.
                     * @return Region Park of the target Bucket for outputting media processing generated files, for example, ap-chongqing. If left empty, it is inheritable from the upper layer.
                     * 
                     */
                    std::string GetRegion() const;

                    /**
                     * 设置Park of the target Bucket for outputting media processing generated files, for example, ap-chongqing. If left empty, it is inheritable from the upper layer.
                     * @param _region Park of the target Bucket for outputting media processing generated files, for example, ap-chongqing. If left empty, it is inheritable from the upper layer.
                     * 
                     */
                    void SetRegion(const std::string& _region);

                    /**
                     * 判断参数 Region 是否已赋值
                     * @return Region 是否已赋值
                     * 
                     */
                    bool RegionHasBeenSet() const;

                private:

                    /**
                     * Target Bucket name for the output files generated by media processing, for example, TopRankVideo-125xxx88. If left empty, the upper-level Bucket is inherited.
                     */
                    std::string m_bucket;
                    bool m_bucketHasBeenSet;

                    /**
                     * Park of the target Bucket for outputting media processing generated files, for example, ap-chongqing. If left empty, it is inheritable from the upper layer.
                     */
                    std::string m_region;
                    bool m_regionHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_MPS_V20190612_MODEL_COSOUTPUTSTORAGE_H_
