/*
 * Copyright (c) 2017-2019 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_FACEID_V20180301_MODEL_DETECTREFLECTLIVENESSANDCOMPAREREQUEST_H_
#define TENCENTCLOUD_FACEID_V20180301_MODEL_DETECTREFLECTLIVENESSANDCOMPAREREQUEST_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/AbstractModel.h>


namespace TencentCloud
{
    namespace Faceid
    {
        namespace V20180301
        {
            namespace Model
            {
                /**
                * DetectReflectLivenessAndCompare request structure.
                */
                class DetectReflectLivenessAndCompareRequest : public AbstractModel
                {
                public:
                    DetectReflectLivenessAndCompareRequest();
                    ~DetectReflectLivenessAndCompareRequest() = default;
                    std::string ToJsonString() const;


                    /**
                     * 获取URL of the liveness detection data package generated by the SDK
                     * @return LiveDataUrl URL of the liveness detection data package generated by the SDK
                     */
                    std::string GetLiveDataUrl() const;

                    /**
                     * 设置URL of the liveness detection data package generated by the SDK
                     * @param LiveDataUrl URL of the liveness detection data package generated by the SDK
                     */
                    void SetLiveDataUrl(const std::string& _liveDataUrl);

                    /**
                     * 判断参数 LiveDataUrl 是否已赋值
                     * @return LiveDataUrl 是否已赋值
                     */
                    bool LiveDataUrlHasBeenSet() const;

                    /**
                     * 获取MD5 hash value (32-bit) of the liveness detection data package generated by the SDK, which is used to verify the LiveData consistency.
                     * @return LiveDataMd5 MD5 hash value (32-bit) of the liveness detection data package generated by the SDK, which is used to verify the LiveData consistency.
                     */
                    std::string GetLiveDataMd5() const;

                    /**
                     * 设置MD5 hash value (32-bit) of the liveness detection data package generated by the SDK, which is used to verify the LiveData consistency.
                     * @param LiveDataMd5 MD5 hash value (32-bit) of the liveness detection data package generated by the SDK, which is used to verify the LiveData consistency.
                     */
                    void SetLiveDataMd5(const std::string& _liveDataMd5);

                    /**
                     * 判断参数 LiveDataMd5 是否已赋值
                     * @return LiveDataMd5 是否已赋值
                     */
                    bool LiveDataMd5HasBeenSet() const;

                    /**
                     * 获取URL of the target image for comparison
                     * @return ImageUrl URL of the target image for comparison
                     */
                    std::string GetImageUrl() const;

                    /**
                     * 设置URL of the target image for comparison
                     * @param ImageUrl URL of the target image for comparison
                     */
                    void SetImageUrl(const std::string& _imageUrl);

                    /**
                     * 判断参数 ImageUrl 是否已赋值
                     * @return ImageUrl 是否已赋值
                     */
                    bool ImageUrlHasBeenSet() const;

                    /**
                     * 获取MD5 hash value (32-bit) of the target image for comparison, which is used to verify the `Image` consistency.
                     * @return ImageMd5 MD5 hash value (32-bit) of the target image for comparison, which is used to verify the `Image` consistency.
                     */
                    std::string GetImageMd5() const;

                    /**
                     * 设置MD5 hash value (32-bit) of the target image for comparison, which is used to verify the `Image` consistency.
                     * @param ImageMd5 MD5 hash value (32-bit) of the target image for comparison, which is used to verify the `Image` consistency.
                     */
                    void SetImageMd5(const std::string& _imageMd5);

                    /**
                     * 判断参数 ImageMd5 是否已赋值
                     * @return ImageMd5 是否已赋值
                     */
                    bool ImageMd5HasBeenSet() const;

                private:

                    /**
                     * URL of the liveness detection data package generated by the SDK
                     */
                    std::string m_liveDataUrl;
                    bool m_liveDataUrlHasBeenSet;

                    /**
                     * MD5 hash value (32-bit) of the liveness detection data package generated by the SDK, which is used to verify the LiveData consistency.
                     */
                    std::string m_liveDataMd5;
                    bool m_liveDataMd5HasBeenSet;

                    /**
                     * URL of the target image for comparison
                     */
                    std::string m_imageUrl;
                    bool m_imageUrlHasBeenSet;

                    /**
                     * MD5 hash value (32-bit) of the target image for comparison, which is used to verify the `Image` consistency.
                     */
                    std::string m_imageMd5;
                    bool m_imageMd5HasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_FACEID_V20180301_MODEL_DETECTREFLECTLIVENESSANDCOMPAREREQUEST_H_
