/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_FACEID_V20180301_MODEL_GENERATEREFLECTSEQUENCEREQUEST_H_
#define TENCENTCLOUD_FACEID_V20180301_MODEL_GENERATEREFLECTSEQUENCEREQUEST_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/AbstractModel.h>


namespace TencentCloud
{
    namespace Faceid
    {
        namespace V20180301
        {
            namespace Model
            {
                /**
                * GenerateReflectSequence request structure.
                */
                class GenerateReflectSequenceRequest : public AbstractModel
                {
                public:
                    GenerateReflectSequenceRequest();
                    ~GenerateReflectSequenceRequest() = default;
                    std::string ToJsonString() const;


                    /**
                     * 获取The resource URL of the data package generated by the SDK.
                     * @return DeviceDataUrl The resource URL of the data package generated by the SDK.
                     * 
                     */
                    std::string GetDeviceDataUrl() const;

                    /**
                     * 设置The resource URL of the data package generated by the SDK.
                     * @param _deviceDataUrl The resource URL of the data package generated by the SDK.
                     * 
                     */
                    void SetDeviceDataUrl(const std::string& _deviceDataUrl);

                    /**
                     * 判断参数 DeviceDataUrl 是否已赋值
                     * @return DeviceDataUrl 是否已赋值
                     * 
                     */
                    bool DeviceDataUrlHasBeenSet() const;

                    /**
                     * 获取The MD5 hash value of the data package generated by the SDK.
                     * @return DeviceDataMd5 The MD5 hash value of the data package generated by the SDK.
                     * 
                     */
                    std::string GetDeviceDataMd5() const;

                    /**
                     * 设置The MD5 hash value of the data package generated by the SDK.
                     * @param _deviceDataMd5 The MD5 hash value of the data package generated by the SDK.
                     * 
                     */
                    void SetDeviceDataMd5(const std::string& _deviceDataMd5);

                    /**
                     * 判断参数 DeviceDataMd5 是否已赋值
                     * @return DeviceDataMd5 是否已赋值
                     * 
                     */
                    bool DeviceDataMd5HasBeenSet() const;

                    /**
                     * 获取1 - silent
2 - blinking
3 - light
4 - blinking + light (default)
                     * @return SecurityLevel 1 - silent
2 - blinking
3 - light
4 - blinking + light (default)
                     * 
                     */
                    std::string GetSecurityLevel() const;

                    /**
                     * 设置1 - silent
2 - blinking
3 - light
4 - blinking + light (default)
                     * @param _securityLevel 1 - silent
2 - blinking
3 - light
4 - blinking + light (default)
                     * 
                     */
                    void SetSecurityLevel(const std::string& _securityLevel);

                    /**
                     * 判断参数 SecurityLevel 是否已赋值
                     * @return SecurityLevel 是否已赋值
                     * 
                     */
                    bool SecurityLevelHasBeenSet() const;

                private:

                    /**
                     * The resource URL of the data package generated by the SDK.
                     */
                    std::string m_deviceDataUrl;
                    bool m_deviceDataUrlHasBeenSet;

                    /**
                     * The MD5 hash value of the data package generated by the SDK.
                     */
                    std::string m_deviceDataMd5;
                    bool m_deviceDataMd5HasBeenSet;

                    /**
                     * 1 - silent
2 - blinking
3 - light
4 - blinking + light (default)
                     */
                    std::string m_securityLevel;
                    bool m_securityLevelHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_FACEID_V20180301_MODEL_GENERATEREFLECTSEQUENCEREQUEST_H_
