/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_FACEID_V20180301_MODEL_GETAMLSCREENINGRESULTRESPONSE_H_
#define TENCENTCLOUD_FACEID_V20180301_MODEL_GETAMLSCREENINGRESULTRESPONSE_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/AbstractModel.h>


namespace TencentCloud
{
    namespace Faceid
    {
        namespace V20180301
        {
            namespace Model
            {
                /**
                * GetAMLScreeningResult response structure.
                */
                class GetAMLScreeningResultResponse : public AbstractModel
                {
                public:
                    GetAMLScreeningResultResponse();
                    ~GetAMLScreeningResultResponse() = default;
                    CoreInternalOutcome Deserialize(const std::string &payload);
                    std::string ToJsonString() const;


                    /**
                     * 获取Screening results: NO-HITS (not hit) / HAS-HITS (hit)
                     * @return ScreeningResult Screening results: NO-HITS (not hit) / HAS-HITS (hit)
                     * 
                     */
                    std::string GetScreeningResult() const;

                    /**
                     * 判断参数 ScreeningResult 是否已赋值
                     * @return ScreeningResult 是否已赋值
                     * 
                     */
                    bool ScreeningResultHasBeenSet() const;

                    /**
                     * 获取Whether continuous monitoring screening is enabled. Default value: false.
                     * @return EnableOngoingScreening Whether continuous monitoring screening is enabled. Default value: false.
                     * 
                     */
                    bool GetEnableOngoingScreening() const;

                    /**
                     * 判断参数 EnableOngoingScreening 是否已赋值
                     * @return EnableOngoingScreening 是否已赋值
                     * 
                     */
                    bool EnableOngoingScreeningHasBeenSet() const;

                    /**
                     * 获取<p>Description of results returned</p>
                     * @return Description <p>Description of results returned</p>
                     * 
                     */
                    std::string GetDescription() const;

                    /**
                     * 判断参数 Description 是否已赋值
                     * @return Description 是否已赋值
                     * 
                     */
                    bool DescriptionHasBeenSet() const;

                    /**
                     * 获取<p>Returned results</p>
                     * @return Result <p>Returned results</p>
                     * 
                     */
                    std::string GetResult() const;

                    /**
                     * 判断参数 Result 是否已赋值
                     * @return Result 是否已赋值
                     * 
                     */
                    bool ResultHasBeenSet() const;

                    /**
                     * 获取<p>The unique identifier of a case generated by a hit screening</p>
                     * @return ScreeningId <p>The unique identifier of a case generated by a hit screening</p>
                     * 
                     */
                    std::string GetScreeningId() const;

                    /**
                     * 判断参数 ScreeningId 是否已赋值
                     * @return ScreeningId 是否已赋值
                     * 
                     */
                    bool ScreeningIdHasBeenSet() const;

                    /**
                     * 获取Screening result time
                     * @return ResultTime Screening result time
                     * 
                     */
                    std::string GetResultTime() const;

                    /**
                     * 判断参数 ResultTime 是否已赋值
                     * @return ResultTime 是否已赋值
                     * 
                     */
                    bool ResultTimeHasBeenSet() const;

                    /**
                     * 获取Returned when there is a hit. A deduplicated list of the hit AML types.
                     * @return AMLTypes Returned when there is a hit. A deduplicated list of the hit AML types.
                     * 
                     */
                    std::vector<std::string> GetAMLTypes() const;

                    /**
                     * 判断参数 AMLTypes 是否已赋值
                     * @return AMLTypes 是否已赋值
                     * 
                     */
                    bool AMLTypesHasBeenSet() const;

                    /**
                     * 获取Returned when there is a hit. A list of hit risk details.
                     * @return HitDetail Returned when there is a hit. A list of hit risk details.
                     * 
                     */
                    std::string GetHitDetail() const;

                    /**
                     * 判断参数 HitDetail 是否已赋值
                     * @return HitDetail 是否已赋值
                     * 
                     */
                    bool HitDetailHasBeenSet() const;

                private:

                    /**
                     * Screening results: NO-HITS (not hit) / HAS-HITS (hit)
                     */
                    std::string m_screeningResult;
                    bool m_screeningResultHasBeenSet;

                    /**
                     * Whether continuous monitoring screening is enabled. Default value: false.
                     */
                    bool m_enableOngoingScreening;
                    bool m_enableOngoingScreeningHasBeenSet;

                    /**
                     * <p>Description of results returned</p>
                     */
                    std::string m_description;
                    bool m_descriptionHasBeenSet;

                    /**
                     * <p>Returned results</p>
                     */
                    std::string m_result;
                    bool m_resultHasBeenSet;

                    /**
                     * <p>The unique identifier of a case generated by a hit screening</p>
                     */
                    std::string m_screeningId;
                    bool m_screeningIdHasBeenSet;

                    /**
                     * Screening result time
                     */
                    std::string m_resultTime;
                    bool m_resultTimeHasBeenSet;

                    /**
                     * Returned when there is a hit. A deduplicated list of the hit AML types.
                     */
                    std::vector<std::string> m_aMLTypes;
                    bool m_aMLTypesHasBeenSet;

                    /**
                     * Returned when there is a hit. A list of hit risk details.
                     */
                    std::string m_hitDetail;
                    bool m_hitDetailHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_FACEID_V20180301_MODEL_GETAMLSCREENINGRESULTRESPONSE_H_
