/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_CLS_V20201016_MODEL_DELIVERCONFIG_H_
#define TENCENTCLOUD_CLS_V20201016_MODEL_DELIVERCONFIG_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/utils/rapidjson/document.h>
#include <tencentcloud/core/utils/rapidjson/writer.h>
#include <tencentcloud/core/utils/rapidjson/stringbuffer.h>
#include <tencentcloud/core/AbstractModel.h>


namespace TencentCloud
{
    namespace Cls
    {
        namespace V20201016
        {
            namespace Model
            {
                /**
                * Shipping configuration input parameter.
                */
                class DeliverConfig : public AbstractModel
                {
                public:
                    DeliverConfig();
                    ~DeliverConfig() = default;
                    void ToJsonObject(rapidjson::Value &value, rapidjson::Document::AllocatorType& allocator) const;
                    CoreInternalOutcome Deserialize(const rapidjson::Value &value);


                    /**
                     * 获取Region information.

Example
ap-guangzhou: Guangzhou region.
ap-nanjing Nanjing region.

For detailed information, see [regions and access endpoints](https://www.tencentcloud.com/document/product/614/18940?from_cn_redirect=1) on the official website.


                     * @return Region Region information.

Example
ap-guangzhou: Guangzhou region.
ap-nanjing Nanjing region.

For detailed information, see [regions and access endpoints](https://www.tencentcloud.com/document/product/614/18940?from_cn_redirect=1) on the official website.


                     * 
                     */
                    std::string GetRegion() const;

                    /**
                     * 设置Region information.

Example
ap-guangzhou: Guangzhou region.
ap-nanjing Nanjing region.

For detailed information, see [regions and access endpoints](https://www.tencentcloud.com/document/product/614/18940?from_cn_redirect=1) on the official website.


                     * @param _region Region information.

Example
ap-guangzhou: Guangzhou region.
ap-nanjing Nanjing region.

For detailed information, see [regions and access endpoints](https://www.tencentcloud.com/document/product/614/18940?from_cn_redirect=1) on the official website.


                     * 
                     */
                    void SetRegion(const std::string& _region);

                    /**
                     * 判断参数 Region 是否已赋值
                     * @return Region 是否已赋值
                     * 
                     */
                    bool RegionHasBeenSet() const;

                    /**
                     * 获取Log topic ID. Obtain the log topic ID through [Get Log Topic List](https://www.tencentcloud.com/document/product/614/56454?from_cn_redirect=1).
                     * @return TopicId Log topic ID. Obtain the log topic ID through [Get Log Topic List](https://www.tencentcloud.com/document/product/614/56454?from_cn_redirect=1).
                     * 
                     */
                    std::string GetTopicId() const;

                    /**
                     * 设置Log topic ID. Obtain the log topic ID through [Get Log Topic List](https://www.tencentcloud.com/document/product/614/56454?from_cn_redirect=1).
                     * @param _topicId Log topic ID. Obtain the log topic ID through [Get Log Topic List](https://www.tencentcloud.com/document/product/614/56454?from_cn_redirect=1).
                     * 
                     */
                    void SetTopicId(const std::string& _topicId);

                    /**
                     * 判断参数 TopicId 是否已赋值
                     * @return TopicId 是否已赋值
                     * 
                     */
                    bool TopicIdHasBeenSet() const;

                    /**
                     * 获取Data delivery scope.

All logs, including daily logs generated by periodic execution of alarm policies and logs generated by policy changes. Default value.

1: Alarm triggering only and restore log
                     * @return Scope Data delivery scope.

All logs, including daily logs generated by periodic execution of alarm policies and logs generated by policy changes. Default value.

1: Alarm triggering only and restore log
                     * 
                     */
                    uint64_t GetScope() const;

                    /**
                     * 设置Data delivery scope.

All logs, including daily logs generated by periodic execution of alarm policies and logs generated by policy changes. Default value.

1: Alarm triggering only and restore log
                     * @param _scope Data delivery scope.

All logs, including daily logs generated by periodic execution of alarm policies and logs generated by policy changes. Default value.

1: Alarm triggering only and restore log
                     * 
                     */
                    void SetScope(const uint64_t& _scope);

                    /**
                     * 判断参数 Scope 是否已赋值
                     * @return Scope 是否已赋值
                     * 
                     */
                    bool ScopeHasBeenSet() const;

                private:

                    /**
                     * Region information.

Example
ap-guangzhou: Guangzhou region.
ap-nanjing Nanjing region.

For detailed information, see [regions and access endpoints](https://www.tencentcloud.com/document/product/614/18940?from_cn_redirect=1) on the official website.


                     */
                    std::string m_region;
                    bool m_regionHasBeenSet;

                    /**
                     * Log topic ID. Obtain the log topic ID through [Get Log Topic List](https://www.tencentcloud.com/document/product/614/56454?from_cn_redirect=1).
                     */
                    std::string m_topicId;
                    bool m_topicIdHasBeenSet;

                    /**
                     * Data delivery scope.

All logs, including daily logs generated by periodic execution of alarm policies and logs generated by policy changes. Default value.

1: Alarm triggering only and restore log
                     */
                    uint64_t m_scope;
                    bool m_scopeHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_CLS_V20201016_MODEL_DELIVERCONFIG_H_
