/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_KMS_V20190118_MODEL_ENCRYPTREQUEST_H_
#define TENCENTCLOUD_KMS_V20190118_MODEL_ENCRYPTREQUEST_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/AbstractModel.h>


namespace TencentCloud
{
    namespace Kms
    {
        namespace V20190118
        {
            namespace Model
            {
                /**
                * Encrypt request structure.
                */
                class EncryptRequest : public AbstractModel
                {
                public:
                    EncryptRequest();
                    ~EncryptRequest() = default;
                    std::string ToJsonString() const;


                    /**
                     * 获取Globally unique ID of the CMK generated by calling the `CreateKey` API
                     * @return KeyId Globally unique ID of the CMK generated by calling the `CreateKey` API
                     * 
                     */
                    std::string GetKeyId() const;

                    /**
                     * 设置Globally unique ID of the CMK generated by calling the `CreateKey` API
                     * @param _keyId Globally unique ID of the CMK generated by calling the `CreateKey` API
                     * 
                     */
                    void SetKeyId(const std::string& _keyId);

                    /**
                     * 判断参数 KeyId 是否已赋值
                     * @return KeyId 是否已赋值
                     * 
                     */
                    bool KeyIdHasBeenSet() const;

                    /**
                     * 获取Encrypted plaintext data. This field must be Base64-encoded. The maximum size of the original data is 4 KB
                     * @return Plaintext Encrypted plaintext data. This field must be Base64-encoded. The maximum size of the original data is 4 KB
                     * 
                     */
                    std::string GetPlaintext() const;

                    /**
                     * 设置Encrypted plaintext data. This field must be Base64-encoded. The maximum size of the original data is 4 KB
                     * @param _plaintext Encrypted plaintext data. This field must be Base64-encoded. The maximum size of the original data is 4 KB
                     * 
                     */
                    void SetPlaintext(const std::string& _plaintext);

                    /**
                     * 判断参数 Plaintext 是否已赋值
                     * @return Plaintext 是否已赋值
                     * 
                     */
                    bool PlaintextHasBeenSet() const;

                    /**
                     * 获取JSON string of key-value pair. If this parameter is specified, the same parameter needs to be provided when the `Decrypt` API is called. It is up to 1,024 characters
                     * @return EncryptionContext JSON string of key-value pair. If this parameter is specified, the same parameter needs to be provided when the `Decrypt` API is called. It is up to 1,024 characters
                     * 
                     */
                    std::string GetEncryptionContext() const;

                    /**
                     * 设置JSON string of key-value pair. If this parameter is specified, the same parameter needs to be provided when the `Decrypt` API is called. It is up to 1,024 characters
                     * @param _encryptionContext JSON string of key-value pair. If this parameter is specified, the same parameter needs to be provided when the `Decrypt` API is called. It is up to 1,024 characters
                     * 
                     */
                    void SetEncryptionContext(const std::string& _encryptionContext);

                    /**
                     * 判断参数 EncryptionContext 是否已赋值
                     * @return EncryptionContext 是否已赋值
                     * 
                     */
                    bool EncryptionContextHasBeenSet() const;

                private:

                    /**
                     * Globally unique ID of the CMK generated by calling the `CreateKey` API
                     */
                    std::string m_keyId;
                    bool m_keyIdHasBeenSet;

                    /**
                     * Encrypted plaintext data. This field must be Base64-encoded. The maximum size of the original data is 4 KB
                     */
                    std::string m_plaintext;
                    bool m_plaintextHasBeenSet;

                    /**
                     * JSON string of key-value pair. If this parameter is specified, the same parameter needs to be provided when the `Decrypt` API is called. It is up to 1,024 characters
                     */
                    std::string m_encryptionContext;
                    bool m_encryptionContextHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_KMS_V20190118_MODEL_ENCRYPTREQUEST_H_
