/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_KMS_V20190118_MODEL_POSTQUANTUMCRYPTOENCRYPTREQUEST_H_
#define TENCENTCLOUD_KMS_V20190118_MODEL_POSTQUANTUMCRYPTOENCRYPTREQUEST_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/AbstractModel.h>


namespace TencentCloud
{
    namespace Kms
    {
        namespace V20190118
        {
            namespace Model
            {
                /**
                * PostQuantumCryptoEncrypt request structure.
                */
                class PostQuantumCryptoEncryptRequest : public AbstractModel
                {
                public:
                    PostQuantumCryptoEncryptRequest();
                    ~PostQuantumCryptoEncryptRequest() = default;
                    std::string ToJsonString() const;


                    /**
                     * 获取Globally unique ID of the CMK generated by calling the `CreateKey` API
                     * @return KeyId Globally unique ID of the CMK generated by calling the `CreateKey` API
                     * 
                     */
                    std::string GetKeyId() const;

                    /**
                     * 设置Globally unique ID of the CMK generated by calling the `CreateKey` API
                     * @param _keyId Globally unique ID of the CMK generated by calling the `CreateKey` API
                     * 
                     */
                    void SetKeyId(const std::string& _keyId);

                    /**
                     * 判断参数 KeyId 是否已赋值
                     * @return KeyId 是否已赋值
                     * 
                     */
                    bool KeyIdHasBeenSet() const;

                    /**
                     * 获取Encrypted plaintext data. This field must be Base64-encoded. The maximum size of the original data is 4 KB.
                     * @return PlainText Encrypted plaintext data. This field must be Base64-encoded. The maximum size of the original data is 4 KB.
                     * 
                     */
                    std::string GetPlainText() const;

                    /**
                     * 设置Encrypted plaintext data. This field must be Base64-encoded. The maximum size of the original data is 4 KB.
                     * @param _plainText Encrypted plaintext data. This field must be Base64-encoded. The maximum size of the original data is 4 KB.
                     * 
                     */
                    void SetPlainText(const std::string& _plainText);

                    /**
                     * 判断参数 PlainText 是否已赋值
                     * @return PlainText 是否已赋值
                     * 
                     */
                    bool PlainTextHasBeenSet() const;

                private:

                    /**
                     * Globally unique ID of the CMK generated by calling the `CreateKey` API
                     */
                    std::string m_keyId;
                    bool m_keyIdHasBeenSet;

                    /**
                     * Encrypted plaintext data. This field must be Base64-encoded. The maximum size of the original data is 4 KB.
                     */
                    std::string m_plainText;
                    bool m_plainTextHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_KMS_V20190118_MODEL_POSTQUANTUMCRYPTOENCRYPTREQUEST_H_
