/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_WEDATA_V20210820_MODEL_INSTANCELOGINFOOPSDTO_H_
#define TENCENTCLOUD_WEDATA_V20210820_MODEL_INSTANCELOGINFOOPSDTO_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/utils/rapidjson/document.h>
#include <tencentcloud/core/utils/rapidjson/writer.h>
#include <tencentcloud/core/utils/rapidjson/stringbuffer.h>
#include <tencentcloud/core/AbstractModel.h>


namespace TencentCloud
{
    namespace Wedata
    {
        namespace V20210820
        {
            namespace Model
            {
                /**
                * Instance log information details
                */
                class InstanceLogInfoOpsDto : public AbstractModel
                {
                public:
                    InstanceLogInfoOpsDto();
                    ~InstanceLogInfoOpsDto() = default;
                    void ToJsonObject(rapidjson::Value &value, rapidjson::Document::AllocatorType& allocator) const;
                    CoreInternalOutcome Deserialize(const rapidjson::Value &value);


                    /**
                     * 获取Instance running log
Note: This field may return null, indicating that no valid value can be obtained.
                     * @return LogInfo Instance running log
Note: This field may return null, indicating that no valid value can be obtained.
                     * 
                     */
                    std::string GetLogInfo() const;

                    /**
                     * 设置Instance running log
Note: This field may return null, indicating that no valid value can be obtained.
                     * @param _logInfo Instance running log
Note: This field may return null, indicating that no valid value can be obtained.
                     * 
                     */
                    void SetLogInfo(const std::string& _logInfo);

                    /**
                     * 判断参数 LogInfo 是否已赋值
                     * @return LogInfo 是否已赋值
                     * 
                     */
                    bool LogInfoHasBeenSet() const;

                    /**
                     * 获取The Yarn log address submitted by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
                     * @return YarnLogInfo The Yarn log address submitted by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
                     * 
                     */
                    std::vector<std::string> GetYarnLogInfo() const;

                    /**
                     * 设置The Yarn log address submitted by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
                     * @param _yarnLogInfo The Yarn log address submitted by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
                     * 
                     */
                    void SetYarnLogInfo(const std::vector<std::string>& _yarnLogInfo);

                    /**
                     * 判断参数 YarnLogInfo 是否已赋值
                     * @return YarnLogInfo 是否已赋值
                     * 
                     */
                    bool YarnLogInfoHasBeenSet() const;

                    /**
                     * 获取The datax log generated by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
                     * @return DataLogInfo The datax log generated by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
                     * 
                     */
                    std::string GetDataLogInfo() const;

                    /**
                     * 设置The datax log generated by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
                     * @param _dataLogInfo The datax log generated by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
                     * 
                     */
                    void SetDataLogInfo(const std::string& _dataLogInfo);

                    /**
                     * 判断参数 DataLogInfo 是否已赋值
                     * @return DataLogInfo 是否已赋值
                     * 
                     */
                    bool DataLogInfoHasBeenSet() const;

                    /**
                     * 获取Third-party Task Execution Log
Note: This field may return null, indicating that no valid value can be obtained.
                     * @return ThirdTaskRunLogInfo Third-party Task Execution Log
Note: This field may return null, indicating that no valid value can be obtained.
                     * 
                     */
                    std::string GetThirdTaskRunLogInfo() const;

                    /**
                     * 设置Third-party Task Execution Log
Note: This field may return null, indicating that no valid value can be obtained.
                     * @param _thirdTaskRunLogInfo Third-party Task Execution Log
Note: This field may return null, indicating that no valid value can be obtained.
                     * 
                     */
                    void SetThirdTaskRunLogInfo(const std::string& _thirdTaskRunLogInfo);

                    /**
                     * 判断参数 ThirdTaskRunLogInfo 是否已赋值
                     * @return ThirdTaskRunLogInfo 是否已赋值
                     * 
                     */
                    bool ThirdTaskRunLogInfoHasBeenSet() const;

                    /**
                     * 获取Third-party Task Log Link Description
Note: This field may return null, indicating that no valid value can be obtained.
                     * @return ThirdTaskLogUrlDesc Third-party Task Log Link Description
Note: This field may return null, indicating that no valid value can be obtained.
                     * 
                     */
                    std::string GetThirdTaskLogUrlDesc() const;

                    /**
                     * 设置Third-party Task Log Link Description
Note: This field may return null, indicating that no valid value can be obtained.
                     * @param _thirdTaskLogUrlDesc Third-party Task Log Link Description
Note: This field may return null, indicating that no valid value can be obtained.
                     * 
                     */
                    void SetThirdTaskLogUrlDesc(const std::string& _thirdTaskLogUrlDesc);

                    /**
                     * 判断参数 ThirdTaskLogUrlDesc 是否已赋值
                     * @return ThirdTaskLogUrlDesc 是否已赋值
                     * 
                     */
                    bool ThirdTaskLogUrlDescHasBeenSet() const;

                    /**
                     * 获取Number of Log Lines
Note: This field may return null, indicating that no valid value can be obtained.
                     * @return LineCount Number of Log Lines
Note: This field may return null, indicating that no valid value can be obtained.
                     * 
                     */
                    int64_t GetLineCount() const;

                    /**
                     * 设置Number of Log Lines
Note: This field may return null, indicating that no valid value can be obtained.
                     * @param _lineCount Number of Log Lines
Note: This field may return null, indicating that no valid value can be obtained.
                     * 
                     */
                    void SetLineCount(const int64_t& _lineCount);

                    /**
                     * 判断参数 LineCount 是否已赋值
                     * @return LineCount 是否已赋值
                     * 
                     */
                    bool LineCountHasBeenSet() const;

                private:

                    /**
                     * Instance running log
Note: This field may return null, indicating that no valid value can be obtained.
                     */
                    std::string m_logInfo;
                    bool m_logInfoHasBeenSet;

                    /**
                     * The Yarn log address submitted by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
                     */
                    std::vector<std::string> m_yarnLogInfo;
                    bool m_yarnLogInfoHasBeenSet;

                    /**
                     * The datax log generated by the instance run
Note: This field may return null, indicating that no valid value can be obtained.
                     */
                    std::string m_dataLogInfo;
                    bool m_dataLogInfoHasBeenSet;

                    /**
                     * Third-party Task Execution Log
Note: This field may return null, indicating that no valid value can be obtained.
                     */
                    std::string m_thirdTaskRunLogInfo;
                    bool m_thirdTaskRunLogInfoHasBeenSet;

                    /**
                     * Third-party Task Log Link Description
Note: This field may return null, indicating that no valid value can be obtained.
                     */
                    std::string m_thirdTaskLogUrlDesc;
                    bool m_thirdTaskLogUrlDescHasBeenSet;

                    /**
                     * Number of Log Lines
Note: This field may return null, indicating that no valid value can be obtained.
                     */
                    int64_t m_lineCount;
                    bool m_lineCountHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_WEDATA_V20210820_MODEL_INSTANCELOGINFOOPSDTO_H_
