/*
 * Copyright (c) 2017-2019 THL A29 Limited, a Tencent company. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_BATCH_V20170312_MODEL_SUBMITJOBREQUEST_H_
#define TENCENTCLOUD_BATCH_V20170312_MODEL_SUBMITJOBREQUEST_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/AbstractModel.h>
#include <tencentcloud/batch/v20170312/model/Placement.h>
#include <tencentcloud/batch/v20170312/model/Job.h>


namespace TencentCloud
{
    namespace Batch
    {
        namespace V20170312
        {
            namespace Model
            {
                /**
                * SubmitJob request structure.
                */
                class SubmitJobRequest : public AbstractModel
                {
                public:
                    SubmitJobRequest();
                    ~SubmitJobRequest() = default;
                    std::string ToJsonString() const;


                    /**
                     * 获取Location information of the submitted job. This parameter allows you to specify information such as the availability zone of the CVM instance with which the job is associated.
                     * @return Placement Location information of the submitted job. This parameter allows you to specify information such as the availability zone of the CVM instance with which the job is associated.
                     */
                    Placement GetPlacement() const;

                    /**
                     * 设置Location information of the submitted job. This parameter allows you to specify information such as the availability zone of the CVM instance with which the job is associated.
                     * @param Placement Location information of the submitted job. This parameter allows you to specify information such as the availability zone of the CVM instance with which the job is associated.
                     */
                    void SetPlacement(const Placement& _placement);

                    /**
                     * 判断参数 Placement 是否已赋值
                     * @return Placement 是否已赋值
                     */
                    bool PlacementHasBeenSet() const;

                    /**
                     * 获取Job information
                     * @return Job Job information
                     */
                    Job GetJob() const;

                    /**
                     * 设置Job information
                     * @param Job Job information
                     */
                    void SetJob(const Job& _job);

                    /**
                     * 判断参数 Job 是否已赋值
                     * @return Job 是否已赋值
                     */
                    bool JobHasBeenSet() const;

                    /**
                     * 获取The string used to guarantee the idempotency of the request, which is generated by the user and must be unique for different requests. The maximum length is 64 ASCII characters. If this parameter is not specified, the idempotency of the request cannot be guaranteed.
                     * @return ClientToken The string used to guarantee the idempotency of the request, which is generated by the user and must be unique for different requests. The maximum length is 64 ASCII characters. If this parameter is not specified, the idempotency of the request cannot be guaranteed.
                     */
                    std::string GetClientToken() const;

                    /**
                     * 设置The string used to guarantee the idempotency of the request, which is generated by the user and must be unique for different requests. The maximum length is 64 ASCII characters. If this parameter is not specified, the idempotency of the request cannot be guaranteed.
                     * @param ClientToken The string used to guarantee the idempotency of the request, which is generated by the user and must be unique for different requests. The maximum length is 64 ASCII characters. If this parameter is not specified, the idempotency of the request cannot be guaranteed.
                     */
                    void SetClientToken(const std::string& _clientToken);

                    /**
                     * 判断参数 ClientToken 是否已赋值
                     * @return ClientToken 是否已赋值
                     */
                    bool ClientTokenHasBeenSet() const;

                private:

                    /**
                     * Location information of the submitted job. This parameter allows you to specify information such as the availability zone of the CVM instance with which the job is associated.
                     */
                    Placement m_placement;
                    bool m_placementHasBeenSet;

                    /**
                     * Job information
                     */
                    Job m_job;
                    bool m_jobHasBeenSet;

                    /**
                     * The string used to guarantee the idempotency of the request, which is generated by the user and must be unique for different requests. The maximum length is 64 ASCII characters. If this parameter is not specified, the idempotency of the request cannot be guaranteed.
                     */
                    std::string m_clientToken;
                    bool m_clientTokenHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_BATCH_V20170312_MODEL_SUBMITJOBREQUEST_H_
