/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_BILLING_V20180709_MODEL_CREATEINSTANCEREQUEST_H_
#define TENCENTCLOUD_BILLING_V20180709_MODEL_CREATEINSTANCEREQUEST_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/AbstractModel.h>


namespace TencentCloud
{
    namespace Billing
    {
        namespace V20180709
        {
            namespace Model
            {
                /**
                * CreateInstance request structure.
                */
                class CreateInstanceRequest : public AbstractModel
                {
                public:
                    CreateInstanceRequest();
                    ~CreateInstanceRequest() = default;
                    std::string ToJsonString() const;


                    /**
                     * 获取ClientToken is an unique, case-sensitive string generated by the client with no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
                     * @return ClientToken ClientToken is an unique, case-sensitive string generated by the client with no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
                     * 
                     */
                    std::string GetClientToken() const;

                    /**
                     * 设置ClientToken is an unique, case-sensitive string generated by the client with no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
                     * @param _clientToken ClientToken is an unique, case-sensitive string generated by the client with no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
                     * 
                     */
                    void SetClientToken(const std::string& _clientToken);

                    /**
                     * 判断参数 ClientToken 是否已赋值
                     * @return ClientToken 是否已赋值
                     * 
                     */
                    bool ClientTokenHasBeenSet() const;

                    /**
                     * 获取Product code.
                     * @return ProductCode Product code.
                     * 
                     */
                    std::string GetProductCode() const;

                    /**
                     * 设置Product code.
                     * @param _productCode Product code.
                     * 
                     */
                    void SetProductCode(const std::string& _productCode);

                    /**
                     * 判断参数 ProductCode 是否已赋值
                     * @return ProductCode 是否已赋值
                     * 
                     */
                    bool ProductCodeHasBeenSet() const;

                    /**
                     * 获取Sub-product code.
                     * @return SubProductCode Sub-product code.
                     * 
                     */
                    std::string GetSubProductCode() const;

                    /**
                     * 设置Sub-product code.
                     * @param _subProductCode Sub-product code.
                     * 
                     */
                    void SetSubProductCode(const std::string& _subProductCode);

                    /**
                     * 判断参数 SubProductCode 是否已赋值
                     * @return SubProductCode 是否已赋值
                     * 
                     */
                    bool SubProductCodeHasBeenSet() const;

                    /**
                     * 获取Region code.
                     * @return RegionCode Region code.
                     * 
                     */
                    std::string GetRegionCode() const;

                    /**
                     * 设置Region code.
                     * @param _regionCode Region code.
                     * 
                     */
                    void SetRegionCode(const std::string& _regionCode);

                    /**
                     * 判断参数 RegionCode 是否已赋值
                     * @return RegionCode 是否已赋值
                     * 
                     */
                    bool RegionCodeHasBeenSet() const;

                    /**
                     * 获取Availability zone code.
                     * @return ZoneCode Availability zone code.
                     * 
                     */
                    std::string GetZoneCode() const;

                    /**
                     * 设置Availability zone code.
                     * @param _zoneCode Availability zone code.
                     * 
                     */
                    void SetZoneCode(const std::string& _zoneCode);

                    /**
                     * 判断参数 ZoneCode 是否已赋值
                     * @return ZoneCode 是否已赋值
                     * 
                     */
                    bool ZoneCodeHasBeenSet() const;

                    /**
                     * 获取Payment mode. Available values: PrePay: upfront charge.
                     * @return PayMode Payment mode. Available values: PrePay: upfront charge.
                     * 
                     */
                    std::string GetPayMode() const;

                    /**
                     * 设置Payment mode. Available values: PrePay: upfront charge.
                     * @param _payMode Payment mode. Available values: PrePay: upfront charge.
                     * 
                     */
                    void SetPayMode(const std::string& _payMode);

                    /**
                     * 判断参数 PayMode 是否已赋值
                     * @return PayMode 是否已赋值
                     * 
                     */
                    bool PayModeHasBeenSet() const;

                    /**
                     * 获取Product detailed information.
                     * @return Parameter Product detailed information.
                     * 
                     */
                    std::string GetParameter() const;

                    /**
                     * 设置Product detailed information.
                     * @param _parameter Product detailed information.
                     * 
                     */
                    void SetParameter(const std::string& _parameter);

                    /**
                     * 判断参数 Parameter 是否已赋值
                     * @return Parameter 是否已赋值
                     * 
                     */
                    bool ParameterHasBeenSet() const;

                    /**
                     * 获取Product quantity, default value is 1.
                     * @return Quantity Product quantity, default value is 1.
                     * 
                     */
                    int64_t GetQuantity() const;

                    /**
                     * 设置Product quantity, default value is 1.
                     * @param _quantity Product quantity, default value is 1.
                     * 
                     */
                    void SetQuantity(const int64_t& _quantity);

                    /**
                     * 判断参数 Quantity 是否已赋值
                     * @return Quantity 是否已赋值
                     * 
                     */
                    bool QuantityHasBeenSet() const;

                    /**
                     * 获取Project id, default value is 0.
                     * @return ProjectId Project id, default value is 0.
                     * 
                     */
                    int64_t GetProjectId() const;

                    /**
                     * 设置Project id, default value is 0.
                     * @param _projectId Project id, default value is 0.
                     * 
                     */
                    void SetProjectId(const int64_t& _projectId);

                    /**
                     * 判断参数 ProjectId 是否已赋值
                     * @return ProjectId 是否已赋值
                     * 
                     */
                    bool ProjectIdHasBeenSet() const;

                    /**
                     * 获取Purchase duration, max number is 36, default value is 1.
                     * @return Period Purchase duration, max number is 36, default value is 1.
                     * 
                     */
                    int64_t GetPeriod() const;

                    /**
                     * 设置Purchase duration, max number is 36, default value is 1.
                     * @param _period Purchase duration, max number is 36, default value is 1.
                     * 
                     */
                    void SetPeriod(const int64_t& _period);

                    /**
                     * 判断参数 Period 是否已赋值
                     * @return Period 是否已赋值
                     * 
                     */
                    bool PeriodHasBeenSet() const;

                    /**
                     * 获取Purchase duration unit. valid values: 
m: month,
y: year. 
default value is: m.
                     * @return PeriodUnit Purchase duration unit. valid values: 
m: month,
y: year. 
default value is: m.
                     * 
                     */
                    std::string GetPeriodUnit() const;

                    /**
                     * 设置Purchase duration unit. valid values: 
m: month,
y: year. 
default value is: m.
                     * @param _periodUnit Purchase duration unit. valid values: 
m: month,
y: year. 
default value is: m.
                     * 
                     */
                    void SetPeriodUnit(const std::string& _periodUnit);

                    /**
                     * 判断参数 PeriodUnit 是否已赋值
                     * @return PeriodUnit 是否已赋值
                     * 
                     */
                    bool PeriodUnitHasBeenSet() const;

                    /**
                     * 获取Auto-renewal flag. valid values: NOTIFY_AND_MANUAL_RENEW: manually renew, NOTIFY_AND_AUTO_RENEW: automatically renew, DISABLE_NOTIFY_AND_MANUAL_RENEW: renewal is disabled. 
default value is NOTIFY_AND_MANUAL_RENEW.
                     * @return RenewFlag Auto-renewal flag. valid values: NOTIFY_AND_MANUAL_RENEW: manually renew, NOTIFY_AND_AUTO_RENEW: automatically renew, DISABLE_NOTIFY_AND_MANUAL_RENEW: renewal is disabled. 
default value is NOTIFY_AND_MANUAL_RENEW.
                     * 
                     */
                    std::string GetRenewFlag() const;

                    /**
                     * 设置Auto-renewal flag. valid values: NOTIFY_AND_MANUAL_RENEW: manually renew, NOTIFY_AND_AUTO_RENEW: automatically renew, DISABLE_NOTIFY_AND_MANUAL_RENEW: renewal is disabled. 
default value is NOTIFY_AND_MANUAL_RENEW.
                     * @param _renewFlag Auto-renewal flag. valid values: NOTIFY_AND_MANUAL_RENEW: manually renew, NOTIFY_AND_AUTO_RENEW: automatically renew, DISABLE_NOTIFY_AND_MANUAL_RENEW: renewal is disabled. 
default value is NOTIFY_AND_MANUAL_RENEW.
                     * 
                     */
                    void SetRenewFlag(const std::string& _renewFlag);

                    /**
                     * 判断参数 RenewFlag 是否已赋值
                     * @return RenewFlag 是否已赋值
                     * 
                     */
                    bool RenewFlagHasBeenSet() const;

                private:

                    /**
                     * ClientToken is an unique, case-sensitive string generated by the client with no more than 64 ASCII characters. for example, ClientToken=123e4567-e89b-12d3-a456-42665544****.
                     */
                    std::string m_clientToken;
                    bool m_clientTokenHasBeenSet;

                    /**
                     * Product code.
                     */
                    std::string m_productCode;
                    bool m_productCodeHasBeenSet;

                    /**
                     * Sub-product code.
                     */
                    std::string m_subProductCode;
                    bool m_subProductCodeHasBeenSet;

                    /**
                     * Region code.
                     */
                    std::string m_regionCode;
                    bool m_regionCodeHasBeenSet;

                    /**
                     * Availability zone code.
                     */
                    std::string m_zoneCode;
                    bool m_zoneCodeHasBeenSet;

                    /**
                     * Payment mode. Available values: PrePay: upfront charge.
                     */
                    std::string m_payMode;
                    bool m_payModeHasBeenSet;

                    /**
                     * Product detailed information.
                     */
                    std::string m_parameter;
                    bool m_parameterHasBeenSet;

                    /**
                     * Product quantity, default value is 1.
                     */
                    int64_t m_quantity;
                    bool m_quantityHasBeenSet;

                    /**
                     * Project id, default value is 0.
                     */
                    int64_t m_projectId;
                    bool m_projectIdHasBeenSet;

                    /**
                     * Purchase duration, max number is 36, default value is 1.
                     */
                    int64_t m_period;
                    bool m_periodHasBeenSet;

                    /**
                     * Purchase duration unit. valid values: 
m: month,
y: year. 
default value is: m.
                     */
                    std::string m_periodUnit;
                    bool m_periodUnitHasBeenSet;

                    /**
                     * Auto-renewal flag. valid values: NOTIFY_AND_MANUAL_RENEW: manually renew, NOTIFY_AND_AUTO_RENEW: automatically renew, DISABLE_NOTIFY_AND_MANUAL_RENEW: renewal is disabled. 
default value is NOTIFY_AND_MANUAL_RENEW.
                     */
                    std::string m_renewFlag;
                    bool m_renewFlagHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_BILLING_V20180709_MODEL_CREATEINSTANCEREQUEST_H_
