/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_MNA_V20210119_MODEL_ADDDEVICEREQUEST_H_
#define TENCENTCLOUD_MNA_V20210119_MODEL_ADDDEVICEREQUEST_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/AbstractModel.h>


namespace TencentCloud
{
    namespace Mna
    {
        namespace V20210119
        {
            namespace Model
            {
                /**
                * AddDevice request structure.
                */
                class AddDeviceRequest : public AbstractModel
                {
                public:
                    AddDeviceRequest();
                    ~AddDeviceRequest() = default;
                    std::string ToJsonString() const;


                    /**
                     * 获取Name of the new device
                     * @return DeviceName Name of the new device
                     * 
                     */
                    std::string GetDeviceName() const;

                    /**
                     * 设置Name of the new device
                     * @param _deviceName Name of the new device
                     * 
                     */
                    void SetDeviceName(const std::string& _deviceName);

                    /**
                     * 判断参数 DeviceName 是否已赋值
                     * @return DeviceName 是否已赋值
                     * 
                     */
                    bool DeviceNameHasBeenSet() const;

                    /**
                     * 获取Remark of the created device
                     * @return Remark Remark of the created device
                     * 
                     */
                    std::string GetRemark() const;

                    /**
                     * 设置Remark of the created device
                     * @param _remark Remark of the created device
                     * 
                     */
                    void SetRemark(const std::string& _remark);

                    /**
                     * 判断参数 Remark 是否已赋值
                     * @return Remark 是否已赋值
                     * 
                     */
                    bool RemarkHasBeenSet() const;

                    /**
                     * 获取base64-encoded key string of the new device, optional. If not filled, automatically generated by the system.
                     * @return DataKey base64-encoded key string of the new device, optional. If not filled, automatically generated by the system.
                     * 
                     */
                    std::string GetDataKey() const;

                    /**
                     * 设置base64-encoded key string of the new device, optional. If not filled, automatically generated by the system.
                     * @param _dataKey base64-encoded key string of the new device, optional. If not filled, automatically generated by the system.
                     * 
                     */
                    void SetDataKey(const std::string& _dataKey);

                    /**
                     * 判断参数 DataKey 是否已赋值
                     * @return DataKey 是否已赋值
                     * 
                     */
                    bool DataKeyHasBeenSet() const;

                    /**
                     * 获取Whether to set the preset key.
true: set preset key.
false: Leave the preset key unset.
                     * @return Encrypted Whether to set the preset key.
true: set preset key.
false: Leave the preset key unset.
                     * 
                     */
                    bool GetEncrypted() const;

                    /**
                     * 设置Whether to set the preset key.
true: set preset key.
false: Leave the preset key unset.
                     * @param _encrypted Whether to set the preset key.
true: set preset key.
false: Leave the preset key unset.
                     * 
                     */
                    void SetEncrypted(const bool& _encrypted);

                    /**
                     * 判断参数 Encrypted 是否已赋值
                     * @return Encrypted 是否已赋值
                     * 
                     */
                    bool EncryptedHasBeenSet() const;

                    /**
                     * 获取Access environment. 0: public cloud gateway; 1: private gateway; 2: public cloud gateway and private gateway. By default if left blank, public cloud gateway.
specific meaning
Public cloud gateway: The device can only integrate with the public cloud gateway (nearby access).
Private gateway: The device can only integrate with the already launched private gateway (nearby access or fixed ip integration).
Public cloud gateway and private gateway: The device can also integrate with the public cloud gateway and the already launched private gateway (connected to nearby or fixed ip access).
                     * @return AccessScope Access environment. 0: public cloud gateway; 1: private gateway; 2: public cloud gateway and private gateway. By default if left blank, public cloud gateway.
specific meaning
Public cloud gateway: The device can only integrate with the public cloud gateway (nearby access).
Private gateway: The device can only integrate with the already launched private gateway (nearby access or fixed ip integration).
Public cloud gateway and private gateway: The device can also integrate with the public cloud gateway and the already launched private gateway (connected to nearby or fixed ip access).
                     * 
                     */
                    int64_t GetAccessScope() const;

                    /**
                     * 设置Access environment. 0: public cloud gateway; 1: private gateway; 2: public cloud gateway and private gateway. By default if left blank, public cloud gateway.
specific meaning
Public cloud gateway: The device can only integrate with the public cloud gateway (nearby access).
Private gateway: The device can only integrate with the already launched private gateway (nearby access or fixed ip integration).
Public cloud gateway and private gateway: The device can also integrate with the public cloud gateway and the already launched private gateway (connected to nearby or fixed ip access).
                     * @param _accessScope Access environment. 0: public cloud gateway; 1: private gateway; 2: public cloud gateway and private gateway. By default if left blank, public cloud gateway.
specific meaning
Public cloud gateway: The device can only integrate with the public cloud gateway (nearby access).
Private gateway: The device can only integrate with the already launched private gateway (nearby access or fixed ip integration).
Public cloud gateway and private gateway: The device can also integrate with the public cloud gateway and the already launched private gateway (connected to nearby or fixed ip access).
                     * 
                     */
                    void SetAccessScope(const int64_t& _accessScope);

                    /**
                     * 判断参数 AccessScope 是否已赋值
                     * @return AccessScope 是否已赋值
                     * 
                     */
                    bool AccessScopeHasBeenSet() const;

                    /**
                     * 获取license payment method 
Monthly authorization 
Permanent license 
If not specified, it defaults to monthly authorization. To permanently license a device, you need to call the OrderPerLicense API to pay the authorization fee. Otherwise, the device cannot be used.
                     * @return LicensePayMode license payment method 
Monthly authorization 
Permanent license 
If not specified, it defaults to monthly authorization. To permanently license a device, you need to call the OrderPerLicense API to pay the authorization fee. Otherwise, the device cannot be used.
                     * 
                     */
                    int64_t GetLicensePayMode() const;

                    /**
                     * 设置license payment method 
Monthly authorization 
Permanent license 
If not specified, it defaults to monthly authorization. To permanently license a device, you need to call the OrderPerLicense API to pay the authorization fee. Otherwise, the device cannot be used.
                     * @param _licensePayMode license payment method 
Monthly authorization 
Permanent license 
If not specified, it defaults to monthly authorization. To permanently license a device, you need to call the OrderPerLicense API to pay the authorization fee. Otherwise, the device cannot be used.
                     * 
                     */
                    void SetLicensePayMode(const int64_t& _licensePayMode);

                    /**
                     * 判断参数 LicensePayMode 是否已赋值
                     * @return LicensePayMode 是否已赋值
                     * 
                     */
                    bool LicensePayModeHasBeenSet() const;

                    /**
                     * 获取Device group name. Optional. Reserved parameter. GroupId must be imported when grouping is required.
                     * @return GroupName Device group name. Optional. Reserved parameter. GroupId must be imported when grouping is required.
                     * 
                     */
                    std::string GetGroupName() const;

                    /**
                     * 设置Device group name. Optional. Reserved parameter. GroupId must be imported when grouping is required.
                     * @param _groupName Device group name. Optional. Reserved parameter. GroupId must be imported when grouping is required.
                     * 
                     */
                    void SetGroupName(const std::string& _groupName);

                    /**
                     * 判断参数 GroupName 是否已赋值
                     * @return GroupName 是否已赋值
                     * 
                     */
                    bool GroupNameHasBeenSet() const;

                    /**
                     * 获取Device group ID. Optional. If not filled, the default device is not grouped.
                     * @return GroupId Device group ID. Optional. If not filled, the default device is not grouped.
                     * 
                     */
                    std::string GetGroupId() const;

                    /**
                     * 设置Device group ID. Optional. If not filled, the default device is not grouped.
                     * @param _groupId Device group ID. Optional. If not filled, the default device is not grouped.
                     * 
                     */
                    void SetGroupId(const std::string& _groupId);

                    /**
                     * 判断参数 GroupId 是否已赋值
                     * @return GroupId 是否已赋值
                     * 
                     */
                    bool GroupIdHasBeenSet() const;

                    /**
                     * 获取No traffic processing method for the device. 0: pay-as-you-go, 1: truncate and accelerate
                     * @return FlowTrunc No traffic processing method for the device. 0: pay-as-you-go, 1: truncate and accelerate
                     * 
                     */
                    int64_t GetFlowTrunc() const;

                    /**
                     * 设置No traffic processing method for the device. 0: pay-as-you-go, 1: truncate and accelerate
                     * @param _flowTrunc No traffic processing method for the device. 0: pay-as-you-go, 1: truncate and accelerate
                     * 
                     */
                    void SetFlowTrunc(const int64_t& _flowTrunc);

                    /**
                     * 判断参数 FlowTrunc 是否已赋值
                     * @return FlowTrunc 是否已赋值
                     * 
                     */
                    bool FlowTruncHasBeenSet() const;

                private:

                    /**
                     * Name of the new device
                     */
                    std::string m_deviceName;
                    bool m_deviceNameHasBeenSet;

                    /**
                     * Remark of the created device
                     */
                    std::string m_remark;
                    bool m_remarkHasBeenSet;

                    /**
                     * base64-encoded key string of the new device, optional. If not filled, automatically generated by the system.
                     */
                    std::string m_dataKey;
                    bool m_dataKeyHasBeenSet;

                    /**
                     * Whether to set the preset key.
true: set preset key.
false: Leave the preset key unset.
                     */
                    bool m_encrypted;
                    bool m_encryptedHasBeenSet;

                    /**
                     * Access environment. 0: public cloud gateway; 1: private gateway; 2: public cloud gateway and private gateway. By default if left blank, public cloud gateway.
specific meaning
Public cloud gateway: The device can only integrate with the public cloud gateway (nearby access).
Private gateway: The device can only integrate with the already launched private gateway (nearby access or fixed ip integration).
Public cloud gateway and private gateway: The device can also integrate with the public cloud gateway and the already launched private gateway (connected to nearby or fixed ip access).
                     */
                    int64_t m_accessScope;
                    bool m_accessScopeHasBeenSet;

                    /**
                     * license payment method 
Monthly authorization 
Permanent license 
If not specified, it defaults to monthly authorization. To permanently license a device, you need to call the OrderPerLicense API to pay the authorization fee. Otherwise, the device cannot be used.
                     */
                    int64_t m_licensePayMode;
                    bool m_licensePayModeHasBeenSet;

                    /**
                     * Device group name. Optional. Reserved parameter. GroupId must be imported when grouping is required.
                     */
                    std::string m_groupName;
                    bool m_groupNameHasBeenSet;

                    /**
                     * Device group ID. Optional. If not filled, the default device is not grouped.
                     */
                    std::string m_groupId;
                    bool m_groupIdHasBeenSet;

                    /**
                     * No traffic processing method for the device. 0: pay-as-you-go, 1: truncate and accelerate
                     */
                    int64_t m_flowTrunc;
                    bool m_flowTruncHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_MNA_V20210119_MODEL_ADDDEVICEREQUEST_H_
