/*
 * Copyright (c) 2017-2025 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TENCENTCLOUD_CSIP_V20221121_MODEL_DESCRIBEAIANALYSISROBOTINFOREQUEST_H_
#define TENCENTCLOUD_CSIP_V20221121_MODEL_DESCRIBEAIANALYSISROBOTINFOREQUEST_H_

#include <string>
#include <vector>
#include <map>
#include <tencentcloud/core/AbstractModel.h>


namespace TencentCloud
{
    namespace Csip
    {
        namespace V20221121
        {
            namespace Model
            {
                /**
                * DescribeAIAnalysisRobotInfo request structure.
                */
                class DescribeAIAnalysisRobotInfoRequest : public AbstractModel
                {
                public:
                    DescribeAIAnalysisRobotInfoRequest();
                    ~DescribeAIAnalysisRobotInfoRequest() = default;
                    std::string ToJsonString() const;


                    /**
                     * 获取<p>Access type. 0/Not imported: WeCom url configuration access. 1: WeCom QR code scan access. 2: WeChat QR code scan access. 3: QQ username and password access. 4: Lark username and password access. 5: DingTalk username and password access</p>
                     * @return AccessType <p>Access type. 0/Not imported: WeCom url configuration access. 1: WeCom QR code scan access. 2: WeChat QR code scan access. 3: QQ username and password access. 4: Lark username and password access. 5: DingTalk username and password access</p>
                     * 
                     */
                    int64_t GetAccessType() const;

                    /**
                     * 设置<p>Access type. 0/Not imported: WeCom url configuration access. 1: WeCom QR code scan access. 2: WeChat QR code scan access. 3: QQ username and password access. 4: Lark username and password access. 5: DingTalk username and password access</p>
                     * @param _accessType <p>Access type. 0/Not imported: WeCom url configuration access. 1: WeCom QR code scan access. 2: WeChat QR code scan access. 3: QQ username and password access. 4: Lark username and password access. 5: DingTalk username and password access</p>
                     * 
                     */
                    void SetAccessType(const int64_t& _accessType);

                    /**
                     * 判断参数 AccessType 是否已赋值
                     * @return AccessType 是否已赋值
                     * 
                     */
                    bool AccessTypeHasBeenSet() const;

                    /**
                     * 获取<p>Create a Bot account ID for QQ, Lark, or DingTalk</p>
                     * @return AccountId <p>Create a Bot account ID for QQ, Lark, or DingTalk</p>
                     * 
                     */
                    std::string GetAccountId() const;

                    /**
                     * 设置<p>Create a Bot account ID for QQ, Lark, or DingTalk</p>
                     * @param _accountId <p>Create a Bot account ID for QQ, Lark, or DingTalk</p>
                     * 
                     */
                    void SetAccountId(const std::string& _accountId);

                    /**
                     * 判断参数 AccountId 是否已赋值
                     * @return AccountId 是否已赋值
                     * 
                     */
                    bool AccountIdHasBeenSet() const;

                    /**
                     * 获取<p>Create a Bot key for QQ/Lark/DingTalk</p>
                     * @return Secret <p>Create a Bot key for QQ/Lark/DingTalk</p>
                     * 
                     */
                    std::string GetSecret() const;

                    /**
                     * 设置<p>Create a Bot key for QQ/Lark/DingTalk</p>
                     * @param _secret <p>Create a Bot key for QQ/Lark/DingTalk</p>
                     * 
                     */
                    void SetSecret(const std::string& _secret);

                    /**
                     * 判断参数 Secret 是否已赋值
                     * @return Secret 是否已赋值
                     * 
                     */
                    bool SecretHasBeenSet() const;

                    /**
                     * 获取<p>Preset bot name. If empty, it will be generated by the backend.</p>
                     * @return BotName <p>Preset bot name. If empty, it will be generated by the backend.</p>
                     * 
                     */
                    std::string GetBotName() const;

                    /**
                     * 设置<p>Preset bot name. If empty, it will be generated by the backend.</p>
                     * @param _botName <p>Preset bot name. If empty, it will be generated by the backend.</p>
                     * 
                     */
                    void SetBotName(const std::string& _botName);

                    /**
                     * 判断参数 BotName 是否已赋值
                     * @return BotName 是否已赋值
                     * 
                     */
                    bool BotNameHasBeenSet() const;

                private:

                    /**
                     * <p>Access type. 0/Not imported: WeCom url configuration access. 1: WeCom QR code scan access. 2: WeChat QR code scan access. 3: QQ username and password access. 4: Lark username and password access. 5: DingTalk username and password access</p>
                     */
                    int64_t m_accessType;
                    bool m_accessTypeHasBeenSet;

                    /**
                     * <p>Create a Bot account ID for QQ, Lark, or DingTalk</p>
                     */
                    std::string m_accountId;
                    bool m_accountIdHasBeenSet;

                    /**
                     * <p>Create a Bot key for QQ/Lark/DingTalk</p>
                     */
                    std::string m_secret;
                    bool m_secretHasBeenSet;

                    /**
                     * <p>Preset bot name. If empty, it will be generated by the backend.</p>
                     */
                    std::string m_botName;
                    bool m_botNameHasBeenSet;

                };
            }
        }
    }
}

#endif // !TENCENTCLOUD_CSIP_V20221121_MODEL_DESCRIBEAIANALYSISROBOTINFOREQUEST_H_
